### ISSUE TITLE
2.10.1 源码运行无法启动成功   able 'dataeasev2demo.xpack_report_info' doesn't exist

### ISSUE THREAD

**Issue by SuperManYo** [dataease/dataease#12433]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
启动失败

**Bug 描述**
本地源码运行时  找不到 xpack_report_info 表；

**Bug 重现步骤(有截图更好)**
---------------------------------
SQL State  : 42S02
Error Code : 1146
Message    : Table 'dataeasev2demo.xpack_report_info' doesn't exist
Location   : db/migration/V2.10.1__ddl.sql (D:\DataEaseCode\dataease-2.10.1\core\core-backend\target\classes\db\migration\V2.10.1__ddl.sql)
Line       : 8
Statement  : ALTER TABLE `xpack_report_info`
    ADD COLUMN `show_watermark` tinyint(1) NOT NULL DEFAULT 0 COMMENT '显示水印' AFTER `rid`

	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:252)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:214)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:133)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:65)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:57)
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:56)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:374)
	... 48 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: Table 'dataeasev2demo.xpack_report_info' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:767)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:652)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:210)
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:89)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:206)
	... 54 common frames omitted

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这里确实是我们的疏忽。
您可以把这条SQL语句删了重新执行一下。

**Comment by xuwei-fit2cloud** [comment]
SQL代码：
https://github.com/dataease/dataease/blob/525bbd7540b1ca001bd5a4826aa1c6285f7d414e/core/core-backend/src/main/resources/db/migration/V2.10.1__ddl.sql#L8C14-L8C31

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
