### ISSUE TITLE
[Bug]带中文名的表格导出的时候，能正常导出，但后台日志有编码异常输出，应该需要在源码中把文件名转成UTF-8编码。

### ISSUE THREAD

**Issue by zhangjie0303** [dataease/dataease#12478]
**DataEase 版本**

2.9.0
**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
必现，带中文名的表格导出的时候，能正常导出，但后台日志有编码格式异常，搜了下修复方案，
在导出的时候，带中文的文件名URLEncoder.encode一下就OK了，没试，觉得能解决，由于我是安装包安装的，改源码还得更换安装方式，就不提pr了，解决方式参考：https://blog.csdn.net/weixin_45131680/article/details/139142582

日志如下：
2024-09-26 09:13:39.478 WARN  --- [io-8100-exec-68] o.apache.coyote.http11.Http11Processor   : The HTTP response header [Content-disposition] with value [attachment;filename=明细表
.xlsx] has been removed from the response because it is invalid
java.lang.IllegalArgumentException: The Unicode character [明] at code point [26,126] cannot be encoded as it is outside the permitted range of 0 to 255
    at org.apache.tomcat.util.buf.MessageBytes.toBytesSimple(MessageBytes.java:310)
    at org.apache.tomcat.util.buf.MessageBytes.toBytes(MessageBytes.java:283)
    at org.apache.coyote.http11.Http11OutputBuffer.write(Http11OutputBuffer.java:385)
    at org.apache.coyote.http11.Http11OutputBuffer.sendHeader(Http11OutputBuffer.java:364)
    at org.apache.coyote.http11.Http11Processor.prepareResponse(Http11Processor.java:1047)
    at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:377)
    at org.apache.coyote.Response.action(Response.java:210)
    at org.apache.coyote.Response.sendHeaders(Response.java:454)
    at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:285)
    at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:265)
    at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:136)
    at org.springframework.web.context.request.async.StandardServletAsyncWebRequest$LifecycleServletOutputStream.flush(StandardServletAsyncWebRequest.java:389)
    at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.flush(ZipArchiveOutputStream.java:974)
    at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:412)
    at java.base/sun.nio.cs.StreamEncoder.lockedFlush(StreamEncoder.java:214)
    at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:201)
    at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:262)
    at org.apache.poi.xssf.streaming.SXSSFWorkbook.copyStreamAndInjectWorksheet(SXSSFWorkbook.java:520)
    at org.apache.poi.xssf.streaming.SXSSFWorkbook.injectData(SXSSFWorkbook.java:409)
    at org.apache.poi.xssf.streaming.SXSSFWorkbook.write(SXSSFWorkbook.java:959)
    at io.dataease.chart.server.ChartDataServer.innerExportDetails(ChartDataServer.java:145)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.base/java.lang.reflect.Method.invoke(Method.java:580)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
    at io.dataease.filter.HtmlResourceFilter.doFilter(HtmlResourceFilter.java:42)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
    at io.dataease.license.config.LicSq.doFilter(c:38)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
    at io.dataease.auth.filter.TokenFilter.doFilter(TokenFilter.java:51)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
    at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
    at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
    at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
    at java.base/java.lang.Thread.run(Thread.java:1583)
2024-09-26 09:14:19.168 INFO  --- [ [_default_]-46] io.dataease.listener.MyCacheListener     : 'CREATED' : [1eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsIm9pZCI6MSwiZXhwIjoxNz
I3MzEzMzU5fQ.BO7YHjM7kzIj4gRQaPSAoMbRu221o7u00Hec1TzIh3o] --> 1

**Bug 重现步骤(有截图更好)**
1. 建一张有中文名的表格
2. 导出
3. 能正常导出，但后台日志有异常。

**Bug修复方案**
2.9.0源码中：
vim ./core/core-backend/src/main/java/io/dataease/chart/server/ChartDataServer.java
第144行：
response.setHeader("Content-disposition", "attachment;filename=" + request.getViewName() + ".xlsx");
改成：
response.setHeader("Content-disposition", "attachment;filename=" + URLEncoder.encode(request.getViewName(),"UTF-8") + ".xlsx");

**Bug修复分析**
之所以未影响最终导出的表，是因为此编码问题只影响response中的header部分，即第145行wb.write(outputStream)失败后，包头里缺失了"Content-disposition"而已，并不影响实际的表格内容，具体参见下图：
![f8535f548550f61805594cba34a575c](https://github.com/user-attachments/assets/ea88866d-f724-40d6-92ff-a142442e6068)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行优化；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
