### ISSUE TITLE
[Question] 为什么数据库连接不上啊，用户名密码是对的

### ISSUE THREAD

**Issue by andrewdeng318** [dataease/dataease#14055]
**请描述您的问题.**
        ... 37 common frames omitted
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:438)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:189)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:550)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:111)

**Comment by xuwei-fit2cloud** [comment]
Access denied for user 'root'@'localhost' (using password: YES)
可以检查一下数据源中填入的root账号是否允许外部访问。

**Comment by andrewdeng318** [comment]
本地通过mysql命令可以连接上，但是无法使用GUI连接上，然后程序也连接不上，非常奇怪

**Comment by maninhill** [comment]
这个请自行搜索解决，应该是环境问题。

**Comment by xuwei-fit2cloud** [comment]
可以参考一下：
https://blog.51cto.com/u_15966109/6082678
