### ISSUE TITLE
仪表盘更新失败，以时间同步设置[Question]

### ISSUE THREAD

**Issue by BXYYZ** [dataease/dataease#2826]
**请描述您的问题.**
日志报错 数据集为SQL数据集 以SQL查询语句 仪表盘更新失败，重启服务后恢复正常；但SQL数据集预览数据是存在数据且正常更新

2022-08-11 07:54:29,018 [clusterScheduler_Worker-10] ERROR i.d.s.dataset.ExtractDataService ? - Method[saveErrorLog][Extract data error: 6a2868b7-97d3-499d-817c-8fde3e4312ee]
org.pentaho.di.core.exception.KettleXMLException: 
Unable to create webresult from XML

Error reading information from XML string : 
<?xml version="1.0" encoding="UTF-8"?>
Premature end of file.

        at org.pentaho.di.www.WebResult.fromXMLString(WebResult.java:108)
        at org.pentaho.di.trans.Trans.sendToSlaveServer(Trans.java:4317)
        at io.dataease.service.dataset.ExtractDataService.extractData(ExtractDataService.java:767)
        at io.dataease.service.dataset.ExtractDataService.extractDataByKettle(ExtractDataService.java:561)
        at io.dataease.service.dataset.ExtractDataService.extractData(ExtractDataService.java:433)
        at io.dataease.service.dataset.ExtractDataService.extractData(ExtractDataService.java:314)
        at io.dataease.job.sechedule.ExtractDataJob.businessExecute(ExtractDataJob.java:18)
        at io.dataease.job.sechedule.DeScheduleJob.execute(DeScheduleJob.java:27)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.pentaho.di.core.exception.KettleXMLException: 
Error reading information from XML string : 
<?xml version="1.0" encoding="UTF-8"?>
Premature end of file.

        at org.pentaho.di.core.xml.XMLHandler.loadXMLString(XMLHandler.java:755)
        at org.pentaho.di.core.xml.XMLHandler.loadXMLString(XMLHandler.java:735)
        at org.pentaho.di.core.xml.XMLHandler.loadXMLString(XMLHandler.java:708)
        at org.pentaho.di.www.WebResult.fromXMLString(WebResult.java:103)
        ... 9 common frames omitted
Caused by: org.xml.sax.SAXParseException: Premature end of file.
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at org.pentaho.di.core.xml.XMLHandler.loadXMLString(XMLHandler.java:746)
        ... 12 common frames omitted
2022-08-11 07:54:29,018 [clusterScheduler_Worker-6] ERROR i.d.s.dataset.ExtractDataService ? - Method[saveErrorLog][Extract data error: a1c67fa9-cf87-4120-aeba-825b7c469ec3]
org.pentaho.di.core.exception.KettleXMLException: 
Unable to create webresult from XML

**Comment by BBchicken-9527** [comment]
感谢反馈，嗯...你的意思是说数据集更新sql数据集，仪表板视图没有更新，重启服务可以更新是这个意思吗？

**Comment by BXYYZ** [comment]
对 问题已经解决 kettle参数调整了 定时同步数量太多导致 kettle内存溢出了；
