### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by EddyPan** [dataease/dataease#2956]
**DataEase 版本**： 从v1.11.3升级至v1.13.1

**运行方式(安装包运行 or 源码运行 ?)**：离线包升级

**浏览器版本**：Edge 104.0.1293.63 (正式版本) (64 位)

**数据源**：CLICKHOUSE

**Bug 描述**：从1.11.3升级至1.13.1之后，仪表板报错，报错信息如下：

仪表板中图表组件内报错：
```
      io.dataease.exception.DataEaseException: io.dataease.exception.DataEaseException: SQL ERRORClickHouse exception, code: 1002, host: *.*.*.*, port: 8123; Code: 53. DB::Exception: Cannot convert string 2022-07-01 00:00:00.000 to type DateTime: while executing 'FUNCTION greaterOrEquals(toDateTime(commit_date) : 5, '2022-07-01 00:00:00.000' : 3) -> greaterOrEquals(toDateTime(commit_date), '2022-07-01 00:00:00.000') UInt8 : 6'. (TYPE_MISMATCH) (version 21.12.3.32 (official build))
,无法正常显示
```

DataEase后端服务报错：
```
io.dataease.exception.DataEaseException: SQL ERRORClickHouse exception, code: 1002, host: *.*.*.*, port: 8123; Code: 53. DB::Exception: Cannot convert string 2022-07-01 00:00:00.000 to type DateTime: while executing 'FUNCTION greaterOrEquals(toDateTime(toDateTime(commit_date)) : 11, '2022-07-01 00:00:00.000' : 6) -> greaterOrEquals(toDateTime(toDateTime(commit_date)), '2022-07-01 00:00:00.000') UInt8 : 12'. (TYPE_MISMATCH) (version 21.12.3.32 (official build))

        at io.dataease.exception.DataEaseException.throwException(DataEaseException.java:14)
        at io.dataease.provider.datasource.JdbcProvider.getData(JdbcProvider.java:338)
        at io.dataease.service.chart.ChartViewService.calcData(ChartViewService.java:892)
        at io.dataease.service.chart.ChartViewService.getData(ChartViewService.java:297)
        at io.dataease.service.chart.ChartViewService$$FastClassBySpringCGLIB$$62336a69.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at io.dataease.service.chart.ChartViewService$$EnhancerBySpringCGLIB$$a1180f78.getData(<generated>)
        at io.dataease.service.chart.ChartViewService$$FastClassBySpringCGLIB$$62336a69.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at io.dataease.service.chart.ChartViewService$$EnhancerBySpringCGLIB$$dfa0747c.getData(<generated>)
        at io.dataease.controller.panel.server.LinkServer.viewDetail(LinkServer.java:106)
        at sun.reflect.GeneratedMethodAccessor377.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
```

初步判定系年月选择组件导致，删除组件后可以正常展示

![image](https://user-images.githubusercontent.com/3865193/186834853-578fdbb2-23e3-4ff2-bf05-93ae40236ad7.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已解决，请升级到最新版本。
