### ISSUE TITLE
[Question] 修改代码后如何构建docker镜像？

### ISSUE THREAD

**Issue by huangapple** [dataease/dataease#4225]
我用的是tag 1.17.1的分支
我按自己的需求小修了下代码， 然后要在根目录执行
```
mvn clean package
```
都成功了后
后再执行 
```
docker build --build-arg IMAGE_TAG=1.17.0 -t dataease:test .
```

镜像也构建出来了， 但跑的时候却报错了。
```
2022-12-28 15:32:26,564 ERROR g.springframework.boot.SpringApplication: 856 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kettleFileRepository' defined in class path resource [io/dataease/config/CommonConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.pentaho.di.repository.filerep.KettleFileRepository]: Factory method 'kettleFileRepository' threw exception; nested exception is org.pentaho.di.core.exception.KettleException: 
java.lang.NoClassDefFoundError: org/apache/commons/lang/builder/HashCodeBuilder
org/apache/commons/lang/builder/HashCodeBuilder

	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at io.dataease.Application.main(Application.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.pentaho.di.repository.filerep.KettleFileRepository]: Factory method 'kettleFileRepository' threw exception; nested exception is org.pentaho.di.core.exception.KettleException: 
java.lang.NoClassDefFoundError: org/apache/commons/lang/builder/HashCodeBuilder
org/apache/commons/lang/builder/HashCodeBuilder

	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 28 common frames omitted
Caused by: org.pentaho.di.core.exception.KettleException: 
java.lang.NoClassDefFoundError: org/apache/commons/lang/builder/HashCodeBuilder
org/apache/commons/lang/builder/HashCodeBuilder

	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:163)
	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:101)
	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:82)
	at io.dataease.config.CommonConfig.kettleFileRepository(CommonConfig.java:27)
	at io.dataease.config.CommonConfig$$EnhancerBySpringCGLIB$$1ff88897.CGLIB$kettleFileRepository$1(<generated>)
	at io.dataease.config.CommonConfig$$EnhancerBySpringCGLIB$$1ff88897$$FastClassBySpringCGLIB$$d8268213.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at io.dataease.config.CommonConfig$$EnhancerBySpringCGLIB$$1ff88897.kettleFileRepository(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 29 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang/builder/HashCodeBuilder
	at org.pentaho.di.core.plugins.PluginFolder.hashCode(PluginFolder.java:196)
	at java.util.HashMap.hash(HashMap.java:340)
	at java.util.HashMap.get(HashMap.java:558)
	at org.pentaho.di.core.plugins.JarFileCache.getFileObjects(JarFileCache.java:64)
	at org.pentaho.di.core.plugins.BasePluginType.findAnnotatedClassFiles(BasePluginType.java:399)
	at org.pentaho.di.core.plugins.BasePluginType.registerPluginJars(BasePluginType.java:706)
	at org.pentaho.di.core.plugins.BasePluginType.searchPlugins(BasePluginType.java:185)
	at org.pentaho.di.core.plugins.PluginRegistry.registerType(PluginRegistry.java:605)
	at org.pentaho.di.core.plugins.PluginRegistry.init(PluginRegistry.java:560)
	at org.pentaho.di.core.plugins.PluginRegistry.init(PluginRegistry.java:545)
	at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:117)
	at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:80)
	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:134)
	... 42 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.builder.HashCodeBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 55 common frames omitted

```

**Comment by huangapple** [comment]
是还要在pom.xml添加什么依赖吗？还是我打包docker构建的方式有问题？  有没有相关文档?

**Comment by ywhfzy** [comment]
https://kb.fit2cloud.com/archives/70 看这个

**Comment by huangapple** [comment]
那个好像跟我的操作是一样的啊？？

**Comment by huangapple** [comment]
@ywhfzy @xuwei-fit2cloud

**Comment by huangapple** [comment]
补了几个依赖后成功了

```
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>2.6</version>
        </dependency>

        <dependency>
            <groupId>pentaho</groupId>
            <artifactId>pentaho-platform-api</artifactId>
            <version>8.3.0.18-1084</version>
        </dependency>
```
