### ISSUE TITLE
[Bug]mysql8项目启动时，数据库数据初始化错误

### ISSUE THREAD

**Issue by yangjunzhou861012** [dataease/dataease#4515]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
源码运行
使用工具idea和webstorm
数据库是mysql8.0.31

**浏览器版本**
chrom

**Bug 描述**
当后台启动初始化的时候，数据初始化报错，报错信息如下：
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-02-12 11:35:53,813 ERROR g.springframework.boot.SpringApplication: 856 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V8__demo.sql failed
-----------------------------
SQL State  : HY000
Error Code : 1267
Message    : Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='
Location   : db/migration/V8__demo.sql (F:\cankaoProject\BI\dataease-1.16.0\dataease-1.16.0\backend\target\classes\db\migration\V8__demo.sql)
Line       : 41
Statement  : INSERT INTO  `datasource` (`id`, `name`, `desc`, `type`, `configuration`, `create_time`, `update_time`, `create_by`) VALUES ('76026997-94f9-4a35-96ca-151084638969', 'demo', 'demo', 'mysql', 'ROM9ccqPioJ1SCj70u/B+KCVPfwPyNbqgIgkguMQEbjrQLbGyQLfqnQdH64Nyb+LyW+vDZzSK0SJFxUGAwGxvUtKnmpwinKRZ9OcFiQB10Nq5r/DH4+2F9/dKBs2lQgrwNj5w6MyhRswSKzkfCw5fNndcN2ad990JjOQLYz2Y5M=', '1624247414781', '1624247414781', 'admin')

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at io.dataease.Application.main(Application.java:23)
Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V8__demo.sql failed
-----------------------------
SQL State  : HY000
Error Code : 1267
Message    : Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='
Location   : db/migration/V8__demo.sql (F:\cankaoProject\BI\dataease-1.16.0\dataease-1.16.0\backend\target\classes\db\migration\V8__demo.sql)
Line       : 41
Statement  : INSERT INTO  `datasource` (`id`, `name`, `desc`, `type`, `configuration`, `create_time`, `update_time`, `create_by`) VALUES ('76026997-94f9-4a35-96ca-151084638969', 'demo', 'demo', 'mysql', 'ROM9ccqPioJ1SCj70u/B+KCVPfwPyNbqgIgkguMQEbjrQLbGyQLfqnQdH64Nyb+LyW+vDZzSK0SJFxUGAwGxvUtKnmpwinKRZ9OcFiQB10Nq5r/DH4+2F9/dKBs2lQgrwNj5w6MyhRswSKzkfCw5fNndcN2ad990JjOQLYz2Y5M=', '1624247414781', '1624247414781', 'admin')

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:438)
	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:56)
	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:341)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:338)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:303)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:56)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:207)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:204)
	at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:161)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:204)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:165)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:215)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:164)
	at org.flywaydb.core.Flyway.execute(Flyway.java:538)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:164)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	... 19 common frames omitted
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: 
Migration V8__demo.sql failed
-----------------------------
SQL State  : HY000
Error Code : 1267
Message    : Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='
Location   : db/migration/V8__demo.sql (F:\cankaoProject\BI\dataease-1.16.0\dataease-1.16.0\backend\target\classes\db\migration\V8__demo.sql)
Line       : 41
Statement  : INSERT INTO  `datasource` (`id`, `name`, `desc`, `type`, `configuration`, `create_time`, `update_time`, `create_by`) VALUES ('76026997-94f9-4a35-96ca-151084638969', 'demo', 'demo', 'mysql', 'ROM9ccqPioJ1SCj70u/B+KCVPfwPyNbqgIgkguMQEbjrQLbGyQLfqnQdH64Nyb+LyW+vDZzSK0SJFxUGAwGxvUtKnmpwinKRZ9OcFiQB10Nq5r/DH4+2F9/dKBs2lQgrwNj5w6MyhRswSKzkfCw5fNndcN2ad990JjOQLYz2Y5M=', '1624247414781', '1624247414781', 'admin')

	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:273)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:218)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:82)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.access$000(SqlMigrationExecutor.java:32)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor$1.call(SqlMigrationExecutor.java:70)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor$1.call(SqlMigrationExecutor.java:67)
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:28)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:67)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:434)
	... 39 common frames omitted
Caused by: java.sql.SQLException: Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:241)
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:206)
	... 47 common frames omitted
与目标 VM 断开连接, 地址为: ''127.0.0.1:12739'，传输: '套接字''

进程已结束,退出代码1

**Bug 重现步骤(有截图更好)**
1. idea打开项目源码，设置好本地数据库
2. 启动项目
3.

**Comment by xuwei-fit2cloud** [comment]
您好，可以参考一下在线文档，注意一下database在创建时的编码。
https://dataease.io/docs/faq/configuration_faq/dataease_mysql/#9-dataease-illegal-mix-of-collations-latin1_bin-implicit-and-utf8_general_ci-coercible

**Comment by yangjunzhou861012** [comment]
> 您好，可以参考一下在线文档，注意一下database在创建时的编码。 https://dataease.io/docs/faq/configuration_faq/dataease_mysql/#9-dataease-illegal-mix-of-collations-latin1_bin-implicit-and-utf8_general_ci-coercible

已经设置过数据格式了，但是我看sql脚本基本都是utf8mb4，所以这里也是设置utf8mb4，而且之前改用uft8也是同样的问题
![aaa](https://user-images.githubusercontent.com/18575974/218368217-7240c857-6e73-4674-a908-961829657d71.png)

**Comment by xuwei-fit2cloud** [comment]
![图片](https://user-images.githubusercontent.com/1892127/219310119-90e71287-a63d-46e7-83ce-26cd659dfa0a.png)

上图是我在测试环境中测试的同版本MySQL镜像，默认是没有问题的。您可以再检查一下 collation 的设置，请参考一下我的截图。

**Comment by yangjunzhou861012** [comment]
> 
utf8mb3,我看脚本中默认的sql编码都是utf8mb4吧？

**Comment by yangjunzhou861012** [comment]
> ![图片](https://user-images.githubusercontent.com/1892127/219310119-90e71287-a63d-46e7-83ce-26cd659dfa0a.png)
> 
> 上图是我在测试环境中测试的同版本MySQL镜像，默认是没有问题的。您可以再检查一下 collation 的设置，请参考一下我的截图。


将数据库的字符编码由utf8mb4修改为utf8mb3就能正常启动了，可是看数据库下面的表编码好像都是默认utf8mb4的啊
![image](https://user-images.githubusercontent.com/18575974/219842706-91cef898-0b9b-44d6-8d22-d470d6a8250a.png)
