### ISSUE TITLE
[Bug]由于缺少demo数据源升级v1.18.3无法正常启动

### ISSUE THREAD

**Issue by wan92hen** [dataease/dataease#4643]
**DataEase 版本**
v1.18.3

**Bug 描述**
从 v1.18.1 升级到 v.18.3 时，由于之前删掉了自动初始化出来的 demo 数据源，导致 v1.18.3 启动失败。

**Bug 重现步骤(有截图更好)**
1. 安装 v1.18.1 版本。
2. 删除 demo 数据源。
3. 升级到 v1.18.3 版本。

## 日志
```
2023-02-27 13:44:17,309 ERROR g.springframework.boot.SpringApplication: 856 - Application run failed
java.lang.NullPointerException: null
        at io.dataease.service.datasource.DatasourceService.updateDemoDs(DatasourceService.java:653)
        at io.dataease.service.datasource.DatasourceService$$FastClassBySpringCGLIB$$2ccad08e.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at io.dataease.service.datasource.DatasourceService$$EnhancerBySpringCGLIB$$2918745.updateDemoDs(<generated>)
        at io.dataease.service.datasource.DatasourceService$$FastClassBySpringCGLIB$$2ccad08e.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at io.dataease.service.datasource.DatasourceService$$EnhancerBySpringCGLIB$$d860cad0.updateDemoDs(<generated>)
        at io.dataease.listener.DataSourceInitStartListener.onApplicationEvent(DataSourceInitStartListener.java:29)
        at io.dataease.listener.DataSourceInitStartListener.onApplicationEvent(DataSourceInitStartListener.java:13)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:420)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:377)
        at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:111)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$running$6(SpringApplicationRunListeners.java:79)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
        at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:79)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:341)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
        at io.dataease.Application.main(Application.java:22)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
2023-02-27 13:44:17,347  INFO g.simp.broker.SimpleBrokerMessageHandler: 137 - Stopping...
2023-02-27 13:44:17,347  INFO g.simp.broker.SimpleBrokerMessageHandler: 137 - BrokerAvailabilityEvent[available=false, SimpleBrokerMessageHandler [org.springframework.messaging.simp.broker.DefaultSubscriptionRegistry@3a3b10f4]]
2023-02-27 13:44:17,347  INFO g.simp.broker.SimpleBrokerMessageHandler: 137 - Stopped.
```

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #4641
