### ISSUE TITLE
[Bug]【数据集】SQL 数据集定时同步报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4666]
**DataEase 版本**
1.18.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
SQL 数据集做定时同步的操作的时候就会报错

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/24768910/221792492-a50209df-096c-4f6e-a0a7-c1565633ca13.png)

![image](https://user-images.githubusercontent.com/24768910/221792359-519ce9ac-14f4-400c-ba34-dbc842579068.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，将会在下个版本发布

**Comment by tyler-whz** [comment]
Unable to get queryfields for SQL: 
SELECT `id` AS C_b80bb7740288fda1f201890375a60c8f,`deptname` AS C_cd3474778be497222154e1f771f7ff48 FROM ` (SELECT   s.user_id as id,t.dept_name as deptname from 
sys_user s,sys_dept t where s.dept_id = t.dept_id) AS DE_TEMP`  LIMIT 0, 50000 
Couldn't get field info from [SELECT `id` AS C_b80bb7740288fda1f201890375a60c8f,`deptname` AS C_cd3474778be497222154e1f771f7ff48 FROM ` (SELECT   s.user_id as id,t.dept_name as deptname from 
sys_user s,sys_dept t where s.dept_id = t.dept_id) AS DE_TEMP`  LIMIT 0, 50000 ]
Identifier name ' (SELECT   s.user_id as id,t.dept_name as deptname from 
sys_user s,sys_dept t where s.dept_id = t.d' is too long
	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:264)
	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2054)
	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1872)
	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1951)
	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1921)
	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1904)
	at org.pentaho.di.trans.steps.userdefinedjavaclass.TransformClassBase.<init>(Tran
解析sql数据集合时 多了` ` ，导致失败

**Comment by BBchicken-9527** [comment]
感谢反馈，目前版本次问题已经修复，你可以尝试升级到最新版本体验。

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你现在的版本是最新的吗？目前版本次问题已经修复，你可以尝试升级到最新版本体验。
