### ISSUE TITLE
使用docker离线部署，kettle部署报错

### ISSUE THREAD

**Issue by ingla9988** [dataease/dataease#4690]
按照文档部署：https://dataease.io/docs/installation/offline_installation/
部署完之后kettle有以下报错
 docker logs kettle 日志如下：
#######################################################################
WARNING:  no libwebkitgtk-1.0 detected, some features will be unavailable
    Consider installing the package with apt-get or yum.
    e.g. 'sudo apt-get install libwebkitgtk-1.0-0'
#######################################################################
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
09:45:46,535 WARN  [KarafBoot] Karaf not found in standard dir of './system/karaf' 
09:45:46,547 ERROR [KarafBoot] Error starting Karaf
java.io.FileNotFoundException: Source './system/karaf' does not exist
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1298)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1240)
	at org.pentaho.platform.osgi.KarafBoot.startup(KarafBoot.java:191)
	at org.pentaho.di.osgi.registryExtension.OSGIPluginRegistryExtension.init(OSGIPluginRegistryExtension.java:109)
	at org.pentaho.di.core.plugins.PluginRegistry.init(PluginRegistry.java:565)
	at org.pentaho.di.core.plugins.PluginRegistry.init(PluginRegistry.java:545)
	at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:117)
	at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:80)
	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:133)
	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:100)
	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:81)
	at org.pentaho.di.www.Carte.setKettleEnvironment(Carte.java:241)
	at org.pentaho.di.www.Carte.parseAndRunCommand(Carte.java:234)
	at org.pentaho.di.www.Carte.main(Carte.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)

**Comment by BBchicken-9527** [comment]
感谢反馈，你的服务版本是？建议你使用centos 7.6+去安装，版本过低因为服务器架构问题可能会出现这种依赖失败的问题

**Comment by ingla9988** [comment]
centos 7.9  安装的

**Comment by BBchicken-9527** [comment]
如果你手动安装libwebkitgtk-1.0这个依赖会有问题吗？

**Comment by Sky-shang** [comment]
我也碰到同样的问题。kettle镜像是缺少依赖包吧

**Comment by yongliangZhang** [comment]
此问题在v.118.6 版本仍存在该问题，具体错误信息为：
`java.lang.ClassCastException: org.apache.log4j.ConsoleAppender cannot be cast to org.apache.log4j.Appender
        at#######################################################################
WARNING:  no libwebkitgtk-1.0 detected, some features will be unavailable
    Consider installing the package with apt-get or yum.
    e.g. 'sudo apt-get install libwebkitgtk-1.0-0'
#######################################################################
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
08:09:39,205 WARN  [KarafBoot] Karaf not found in standard dir of './system/karaf' 
08:09:39,218 ERROR [KarafBoot] Error starting Karaf
java.io.FileNotFoundException: Source './system/karaf' does not exist
        at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1298)
        at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1240)
        at org.pentaho.platform.osgi.KarafBoot.startup(KarafBoot.java:191)
        at org.pentaho.di.osgi.registryExtension.OSGIPluginRegistryExtension.init(OSGIPluginRegistryExtension.java:109)
        at org.pentaho.di.core.plugins.PluginRegistry.init(PluginRegistry.java:565)
        at org.pentaho.di.core.plugins.PluginRegistry.init(PluginRegistry.java:545)
        at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:117)
        at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:80)
        at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:133)
        at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:100)
        at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:81)
        at org.pentaho.di.www.Carte.setKettleEnvironment(Carte.java:241)
        at org.pentaho.di.www.Carte.parseAndRunCommand(Carte.java:234)
        at org.pentaho.di.www.Carte.main(Carte.java:164)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
log4j:ERROR Could not create an Appender. Reported error follows.
java.lang.ClassCastException: org.apache.log4j.ConsoleAppender cannot be cast to org.apache.log4j.Appender
        at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:248)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:176)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:191)
        at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:523)
        at org.apache.log4j.xml.DOMConfigurator.parseCategory(DOMConfigurator.java:436)
        at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:1004)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:872)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:755)
        at org.apache.log4j.xml.DOMConfigurator.configure(DOMConfigurator.java:896)
        at org.pentaho.di.core.logging.log4j.Log4jLogging.applyLog4jConfiguration(Log4jLogging.java:101)
        at org.pentaho.di.core.logging.log4j.Log4jLogging.createLogger(Log4jLogging.java:109)
        at org.pentaho.di.core.logging.log4j.Log4jLogging.init(Log4jLogging.java:71)
        at org.pentaho.di.core.KettleClientEnvironment.initLogginPlugins(KettleClientEnvironment.java:157)
        at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:120)
        at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:80)
        at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:133)
        at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:100)
        at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:81)
        at org.pentaho.di.www.Carte.setKettleEnvironment(Carte.java:241)
        at org.pentaho.di.www.Carte.parseAndRunCommand(Carte.java:234)
        at org.pentaho.di.www.Carte.main(Carte.java:164)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)`
docker  镜像版本为： registry.cn-qingdao.aliyuncs.com/dataease/kettle     v8.3-0318
