### ISSUE TITLE
数据集页面加载缓慢

### ISSUE THREAD

**Issue by 512625100** [dataease/dataease#5295]
**请描述您的问题.**
在网络和服务器没有问题的情况下，点击数据集的时候，加载缓慢，需要等六七秒的时间才会加载出数据集，请问这是什么原因导致呢？

**Comment by 512625100** [comment]
> 



> 您这边数据量大概有多大？是否是企业版？

数据量到不大，我把所有的数据集都删除了，加载一样慢，但是我们好像解决了这个问题，代码里面isKettleRunning这个方法好像影响了速度，我把他返回了一个false，就快了，但是没看懂这个方法是干什么用的

**Comment by xuwei-fit2cloud** [comment]
如果是容器部署的或者是内网部署的kettle的话，访问应该不会很慢。
这个方法主要用来判断创建数据集的时候，能否选择定时同步模式，只有当kettle组件处于正常运行状态，才能使用定时同步的功能，所以这个地方的代码我们还不能调整。

**Comment by yongliangZhang** [comment]
此问题在v.118.6 版本仍存在该问题，具体错误信息为：
`java.lang.ClassCastException: org.apache.log4j.ConsoleAppender cannot be cast to org.apache.log4j.Appender
        at#######################################################################
WARNING:  no libwebkitgtk-1.0 detected, some features will be unavailable
    Consider installing the package with apt-get or yum.
    e.g. 'sudo apt-get install libwebkitgtk-1.0-0'
#######################################################################
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
08:09:39,205 WARN  [KarafBoot] Karaf not found in standard dir of './system/karaf' 
08:09:39,218 ERROR [KarafBoot] Error starting Karaf
java.io.FileNotFoundException: Source './system/karaf' does not exist
        at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1298)
        at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1240)
        at org.pentaho.platform.osgi.KarafBoot.startup(KarafBoot.java:191)
        at org.pentaho.di.osgi.registryExtension.OSGIPluginRegistryExtension.init(OSGIPluginRegistryExtension.java:109)
        at org.pentaho.di.core.plugins.PluginRegistry.init(PluginRegistry.java:565)
        at org.pentaho.di.core.plugins.PluginRegistry.init(PluginRegistry.java:545)
        at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:117)
        at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:80)
        at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:133)
        at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:100)
        at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:81)
        at org.pentaho.di.www.Carte.setKettleEnvironment(Carte.java:241)
        at org.pentaho.di.www.Carte.parseAndRunCommand(Carte.java:234)
        at org.pentaho.di.www.Carte.main(Carte.java:164)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
log4j:ERROR Could not create an Appender. Reported error follows.
java.lang.ClassCastException: org.apache.log4j.ConsoleAppender cannot be cast to org.apache.log4j.Appender
        at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:248)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:176)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:191)
        at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:523)
        at org.apache.log4j.xml.DOMConfigurator.parseCategory(DOMConfigurator.java:436)
        at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:1004)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:872)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:755)
        at org.apache.log4j.xml.DOMConfigurator.configure(DOMConfigurator.java:896)
        at org.pentaho.di.core.logging.log4j.Log4jLogging.applyLog4jConfiguration(Log4jLogging.java:101)
        at org.pentaho.di.core.logging.log4j.Log4jLogging.createLogger(Log4jLogging.java:109)
        at org.pentaho.di.core.logging.log4j.Log4jLogging.init(Log4jLogging.java:71)
        at org.pentaho.di.core.KettleClientEnvironment.initLogginPlugins(KettleClientEnvironment.java:157)
        at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:120)
        at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:80)
        at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:133)
        at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:100)
        at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:81)
        at org.pentaho.di.www.Carte.setKettleEnvironment(Carte.java:241)
        at org.pentaho.di.www.Carte.parseAndRunCommand(Carte.java:234)
        at org.pentaho.di.www.Carte.main(Carte.java:164)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)`
docker  镜像版本为： registry.cn-qingdao.aliyuncs.com/dataease/kettle     v8.3-0318
