### ISSUE TITLE
[Question]源码安装后点击仪表板和数据集报错

### ISSUE THREAD

**Issue by xiaoxiao261258** [dataease/dataease#5439]
**请描述您的问题.**

问题版本：1.18.6

1、根据文档中的方法，使用源码方式安装。
https://dataease.io/docs/dev_manual/dev_deployment/compile/

2、登录系统后点击仪表板和数据集等菜单时均会提示如下错误。
2023-06-14 09:16:02,234 ERROR localhost].[/de-api].[dispatcherServlet]: 175 - Servlet.service() for servlet [dispatcherServlet] in context with path [/de-api] threw exception [Request processing failed; nested exception is org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: FUNCTION dataease.GET_V_AUTH_MODEL_ID_P_USE does not exist
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: FUNCTION dataease.GET_V_AUTH_MODEL_ID_P_USE does not exist] with root cause
java.sql.SQLSyntaxErrorException: FUNCTION dataease.GET_V_AUTH_MODEL_ID_P_USE does not exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:371)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at sun.reflect.GeneratedMethodAccessor157.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
        at com.sun.proxy.$Proxy331.execute(Unknown Source)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
        at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:132)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
        at com.sun.proxy.$Proxy330.query(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
        at io.dataease.interceptor.MybatisInterceptor.intercept(MybatisInterceptor.java:38)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
        at com.sun.proxy.$Proxy330.query(Unknown Source)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
        at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
        at com.sun.proxy.$Proxy133.selectList(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
        at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)
        at com.sun.proxy.$Proxy181.panelGroupList(Unknown Source)
        at io.dataease.service.panel.PanelGroupService.tree(PanelGroupService.java:149)
        at io.dataease.service.panel.PanelGroupService$$FastClassBySpringCGLIB$$20a3f209.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at io.dataease.service.panel.PanelGroupService$$EnhancerBySpringCGLIB$$6448adba.tree(<generated>)
        at io.dataease.service.panel.PanelGroupService$$FastClassBySpringCGLIB$$20a3f209.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at io.dataease.service.panel.PanelGroupService$$EnhancerBySpringCGLIB$$d57d079d.tree(<generated>)
        at io.dataease.controller.panel.PanelGroupController.tree(PanelGroupController.java:57)
        at io.dataease.controller.panel.PanelGroupController$$FastClassBySpringCGLIB$$ad811325.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at io.dataease.controller.panel.PanelGroupController$$EnhancerBySpringCGLIB$$a8a6203f.tree(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at io.dataease.commons.filter.SqlFilter.doFilter(SqlFilter.java:69)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

3、查询数据库中 v_auth_model  表是存在的。

mysql> use dataease;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+-----------------------------------------+
| Tables_in_dataease                      |
+-----------------------------------------+
| all_issues                              |
| area_mapping                            |
| area_mapping_global                     |
| chart_group                             |
| chart_view                              |
| chart_view_cache                        |
| chart_view_field                        |
| dataease_code_version                   |
| dataease_version                        |
| dataset_column_permissions              |
| dataset_group                           |
| dataset_row_permissions                 |
| dataset_row_permissions_tree            |
| dataset_sql_log                         |
| dataset_table                           |
| dataset_table_field                     |
| dataset_table_function                  |
| dataset_table_incremental_config        |
| dataset_table_task                      |
| dataset_table_task_log                  |
| dataset_table_union                     |
| datasource                              |
| de_driver                               |
| de_driver_details                       |
| de_engine                               |
| demo_alt_4a                             |
| demo_alt_4a_5a                          |
| demo_alt_5a                             |
| demo_alt_region                         |
| demo_alt_tourist_attractions            |
| demo_alt_tourists_total                 |
| demo_alt_tourists_type                  |
| demo_domestic_epidemic                  |
| demo_gdp_2021                           |
| demo_gdp_by_city                        |
| demo_gdp_by_city_top10                  |
| demo_gdp_by_industry                    |
| demo_gdp_district_top100                |
| demo_gdp_history                        |
| demo_hntv_age                           |
| demo_hntv_keywords                      |
| demo_hntv_labels                        |
| demo_hntv_media                         |
| demo_hntv_messages                      |
| demo_hntv_region                        |
| demo_hntv_shows                         |
| demo_hntv_topics                        |
| demo_stny_carbon dioxide_emissions      |
| demo_stny_carbon_emission_trend         |
| demo_stny_disposable_energy             |
| demo_stny_energy_consumption_proportion |
| demo_stny_energy_consumption_total      |
| demo_stny_province_city_index           |
| file_content                            |
| file_metadata                           |
| issue_list                              |
| license                                 |
| my_plugin                               |
| panel_app_template                      |
| panel_app_template_log                  |
| panel_design                            |
| panel_group                             |
| panel_group_extend                      |
| panel_group_extend_data                 |
| panel_link                              |
| panel_link_jump                         |
| panel_link_jump_info                    |
| panel_link_jump_target_view_info        |
| panel_link_mapping                      |
| panel_outer_params                      |
| panel_outer_params_info                 |
| panel_outer_params_target_view_info     |
| panel_pdf_template                      |
| panel_share                             |
| panel_store                             |
| panel_subject                           |
| panel_template                          |
| panel_view                              |
| panel_view_linkage                      |
| panel_view_linkage_field                |
| panel_watermark                         |
| plugin_sys_menu                         |
| qrtz_blob_triggers                      |
| qrtz_calendars                          |
| qrtz_cron_triggers                      |
| qrtz_fired_triggers                     |
| qrtz_job_details                        |
| qrtz_locks                              |
| qrtz_paused_trigger_grps                |
| qrtz_scheduler_state                    |
| qrtz_simple_triggers                    |
| qrtz_simprop_triggers                   |
| qrtz_triggers                           |
| schedule                                |
| sys_auth                                |
| sys_auth_detail                         |
| sys_background_image                    |
| sys_dept                                |
| sys_external_token                      |
| sys_log                                 |
| sys_login_limit                         |
| sys_menu                                |
| sys_msg                                 |
| sys_msg_channel                         |
| sys_msg_setting                         |
| sys_msg_type                            |
| sys_param_assist                        |
| sys_role                                |
| sys_roles_menus                         |
| sys_startup_job                         |
| sys_task                                |
| sys_task_email                          |
| sys_task_instance                       |
| sys_theme                               |
| sys_theme_item                          |
| sys_user                                |
| sys_user_assist                         |
| sys_users_roles                         |
| system_parameter                        |
| task_instance                           |
| user_key                                |
| v_auth_model                            |
| v_auth_privilege                        |
| v_history_chart_view                    |
+-----------------------------------------+
124 rows in set (0.00 sec)

mysql> 

补充说明：mysql使用8.0.21版本，通过docker安装，相关的配置项通过启动参数设置。
mysql> show variables like "%character%";
+--------------------------+--------------------------------+
| Variable_name            | Value                          |
+--------------------------+--------------------------------+
| character_set_client     | latin1                         |
| character_set_connection | latin1                         |
| character_set_database   | utf8mb4                        |
| character_set_filesystem | binary                         |
| character_set_results    | latin1                         |
| character_set_server     | utf8mb4                        |
| character_set_system     | utf8                           |
| character_sets_dir       | /usr/share/mysql-8.0/charsets/ |
+--------------------------+--------------------------------+
8 rows in set (0.01 sec)

mysql> show variables like "lower_case_table_names";
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| lower_case_table_names | 1     |
+------------------------+-------+
1 row in set (0.01 sec)

mysql> show variables like "group_concat_max_len";
+----------------------+---------+
| Variable_name        | Value   |
+----------------------+---------+
| group_concat_max_len | 1024000 |
+----------------------+---------+
1 row in set (0.00 sec)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，源码部署和开发出现的问题，建议您参考前后端分离部署的在线文档排查下，在线文档地址：https://dataease.io/docs/dev_manual/dev_deployment/tool/

**Comment by xiaoxiao261258** [comment]
> 感谢您的反馈，源码部署和开发出现的问题，建议您参考前后端分离部署的在线文档排查下，在线文档地址：https://dataease.io/docs/dev_manual/dev_deployment/tool/

呃，就是参考这个文档部署的，碰到了问题 :)

**Comment by tjlygdx** [comment]
看一下有没有这个 GET_V_AUTH_MODEL_ID_P_USE  function，
没有的话，清空数据库，然后重启跑一遍试试

**Comment by xiaoxiao261258** [comment]
> 看一下有没有这个 GET_V_AUTH_MODEL_ID_P_USE function， 没有的话，清空数据库，然后重启跑一遍试试

我跟踪了下启动日志，发现似乎是数据库连接的时候有异常。

com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
        at io.dataease.provider.datasource.JdbcProvider.getConnection(JdbcProvider.java:524)
        at io.dataease.provider.datasource.JdbcProvider.checkStatus(JdbcProvider.java:367)
        at io.dataease.plugins.datasource.provider.DefaultJdbcProvider.handleDatasource(DefaultJdbcProvider.java:210)
        at io.dataease.service.datasource.DatasourceService.lambda$handleConnectionPool$1(DatasourceService.java:154)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

但奇怪的是，我在后台尝试连接是ok的。
$ mysql -uroot -ppassword -P3306 -hIP
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 177
Server version: 8.0.21 MySQL Community Server - GPL

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>

**Comment by xiaoxiao261258** [comment]
> > 看一下有没有这个 GET_V_AUTH_MODEL_ID_P_USE function， 没有的话，清空数据库，然后重启跑一遍试试
> 
> 我跟踪了下启动日志，发现似乎是数据库连接的时候有异常。
> 
> com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
> 
> The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829) at com.mysql.cj.jdbc.ConnectionImpl.(ConnectionImpl.java:449) at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242) at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) at io.dataease.provider.datasource.JdbcProvider.getConnection(JdbcProvider.java:524) at io.dataease.provider.datasource.JdbcProvider.checkStatus(JdbcProvider.java:367) at io.dataease.plugins.datasource.provider.DefaultJdbcProvider.handleDatasource(DefaultJdbcProvider.java:210) at io.dataease.service.datasource.DatasourceService.lambda$handleConnectionPool$1(DatasourceService.java:154) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
> 
> 但奇怪的是，我在后台尝试连接是ok的。 $ mysql -uroot -ppassword -P3306 -hIP mysql: [Warning] Using a password on the command line interface can be insecure. Welcome to the MySQL monitor. Commands end with ; or \g. Your MySQL connection id is 177 Server version: 8.0.21 MySQL Community Server - GPL
> 
> Copyright (c) 2000, 2023, Oracle and/or its affiliates.
> 
> Oracle is a registered trademark of Oracle Corporation and/or its affiliates. Other names may be trademarks of their respective owners.
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> mysql>


https://kb.fit2cloud.com/?p=104  【常见问题】Communication link failed 问题汇总
我看到了这个链接，里面提到了一些可能的 Communication link failed ，但我这个好像不太一样。完整日志如下：

2023-06-15 10:19:00,696 DEBUG base.mapper.SysMsgMapper.deleteByExample: 137 - ==>  Preparing: delete from sys_msg WHERE ( create_time < ? )
2023-06-15 10:19:00,697 DEBUG base.mapper.SysMsgMapper.deleteByExample: 137 - ==> Parameters: 1684166400000(Long)
2023-06-15 10:19:00,699 DEBUG base.mapper.SysMsgMapper.deleteByExample: 137 - <==    Updates: 0
2023-06-15 10:19:00,702 DEBUG apper.DatasetTableMapper.selectByExample: 137 - ==>  Preparing: select id, `name`, scene_id, data_source_id, `type`, `mode`, info, create_by, create_time, qrtz_instance, sync_status, last_update_time, sql_variable_details from dataset_table WHERE ( `type` = ? )
2023-06-15 10:19:00,704 DEBUG apper.DatasetTableMapper.selectByExample: 137 - ==> Parameters: custom(String)
2023-06-15 10:19:00,705 DEBUG apper.DatasetTableMapper.selectByExample: 137 - <==      Total: 0
2023-06-15 10:19:00,728 DEBUG ChartViewMapper.selectByExampleWithBLOBs: 137 - ==>  Preparing: select id, `name`, title, scene_id, table_id, `type`, render, result_count, result_mode, create_by, create_time, update_time, style_priority, chart_type, is_plugin, data_from, refresh_view_enable, refresh_unit, refresh_time , x_axis, x_axis_ext, y_axis, y_axis_ext, ext_stack, ext_bubble, custom_attr, custom_style, custom_filter, drill_fields, senior, snapshot, view_fields from chart_view
2023-06-15 10:19:00,729 DEBUG ChartViewMapper.selectByExampleWithBLOBs: 137 - ==> Parameters: 
2023-06-15 10:19:00,821 DEBUG ChartViewMapper.selectByExampleWithBLOBs: 137 - <==      Total: 171
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
        at io.dataease.provider.datasource.JdbcProvider.getConnection(JdbcProvider.java:524)
        at io.dataease.provider.datasource.JdbcProvider.checkStatus(JdbcProvider.java:367)
        at io.dataease.plugins.datasource.provider.DefaultJdbcProvider.handleDatasource(DefaultJdbcProvider.java:210)
        at io.dataease.service.datasource.DatasourceService.lambda$handleConnectionPool$1(DatasourceService.java:154)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
        at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:949)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)
        ... 14 more
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:156)
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
        ... 17 more
2023-06-15 10:19:44,191  INFO ocket.config.WebSocketMessageBrokerStats: 126 - WebSocketSession[0 current WS(0)-HttpStream(0)-HttpPoll(0), 0 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(0)-CONNECTED(0)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], outboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], sockJsScheduler[pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
2023-06-15 10:19:58,940  INFO k.scheduling.quartz.SchedulerFactoryBean: 748 - Starting Quartz Scheduler now, after delay of 60 seconds
