### ISSUE TITLE
[Bug]全新安装,springframework.boot.SpringApplication启动失败数组越界

### ISSUE THREAD

**Issue by zhong914** [dataease/dataease#5452]
**DataEase 版本**

dataease-v1.18.7-online

**运行方式(安装包运行 or 源码运行 ?)**

curl -sSL https://dataease.oss-cn-hangzhou.aliyuncs.com/quick_start.sh | sh

**Bug 描述**
`
  2023-06-14 15:25:37,185 ERROR g.springframework.boot.SpringApplication: 856 - Application run failed
  java.lang.ArrayIndexOutOfBoundsException: 1
          at io.dataease.service.engine.EngineService.initSimpleEngine(EngineService.java:229)
          at io.dataease.service.engine.EngineService$$FastClassBySpringCGLIB$$42c775ae.invoke(<generated>)
          at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
          at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
          at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
          at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
          at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
          at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
          at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
          at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
          at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
          at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
          at io.dataease.service.engine.EngineService$$EnhancerBySpringCGLIB$$f5ee2f68.initSimpleEngine(<generated>)
          at io.dataease.service.engine.EngineService$$FastClassBySpringCGLIB$$42c775ae.invoke(<generated>)
          at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
          at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
          at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
          at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
          at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
          at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
          at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
          at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
          at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
          at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
          at io.dataease.service.engine.EngineService$$EnhancerBySpringCGLIB$$cb66ea3a.initSimpleEngine(<generated>)
          at io.dataease.listener.DataSourceInitStartListener.onApplicationEvent(DataSourceInitStartListener.java:28)
          at io.dataease.listener.DataSourceInitStartListener.onApplicationEvent(DataSourceInitStartListener.java:13)
          at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
          at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
          at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
          at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:420)
          at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:377)
          at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:111)
          at org.springframework.boot.SpringApplicationRunListeners.lambda$running$6(SpringApplicationRunListeners.java:79)
          at java.util.ArrayList.forEach(ArrayList.java:1259)
          at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
          at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
          at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:79)
          at org.springframework.boot.SpringApplication.run(SpringApplication.java:341)
          at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
          at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
          at io.dataease.Application.main(Application.java:22)
          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
          at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
          at java.lang.reflect.Method.invoke(Method.java:498)
          at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
          at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
          at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
          at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
`

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.8版本已处理，请更新版本。
