### ISSUE TITLE
非企业版用户在企业微信上登录DataEase会一直循环报错[Bug]

### ISSUE THREAD

**Issue by BreadmanCheray** [dataease/dataease#5539]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
非企业版用户在企业微信上首次打开DataEase可以正常登陆，当过一段时间再打开DataEase，会话过期了，正常是需要重新输入密码登陆，但登陆页面会不停的反复加载，无法正常登陆。通过在PC端企业微信打开，在移动端企业微信应用上打开和在移动端企业微信上消息窗口打开，发现网页会有明显的变化，在PC端企业微信打开，网址为：http://XXXXX/#/login?redirect=%2F，如果在移动端的自带浏览器上打开，网址是：http://XXXX/app.html#/，但在移动端企业微信应用或者消息窗口打开DataEase的网址，网址会从原来的变成：http://XXXX/app.html?detoken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODc2MzA1MTUsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJhZG1pbiJ9.e8dhfUGozJWaMsrmwr6xemEzJtdBFqOuzpeeyb0jcEE#/,当出现这些，页面就不停的反复加载，app.html?后面会加上detoken=后面带一串东西，然后不停反复提示token错误，一直在反复加载无法登陆进入到DataEase首页。这种情况是不是因为企业版的企业微信绑定后自动登陆到DataEase的功能，影响到非企业版用户在没有绑定企业微信帐号，导致无法正常登陆？
**Bug 重现步骤(有截图更好)**
1.
![b4fb4160-967e-4ef5-8c67-8b8db9acfcfb](https://github.com/dataease/dataease/assets/119944880/ea132eca-c55a-4949-bdfe-b36d04bfc8e2)

2.
![987c9839-d537-4da0-9c9b-ef162584542b](https://github.com/dataease/dataease/assets/119944880/07b236ec-1603-43c9-87fc-5f8fa5c82170)

3.
![0e3c9a87-3e02-46d0-ab91-60f6112cf789](https://github.com/dataease/dataease/assets/119944880/351ee92c-b6fc-4bce-b5b9-20499a1a55d3)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的这个问题，方便看一下后台的日志吗

**Comment by BreadmanCheray** [comment]
> 感谢反馈，目前测试环境没有发现你说的这个问题，方便看一下后台的日志吗

后台日志我可以从哪里导出来？

**Comment by BreadmanCheray** [comment]
2023-07-03 10:03:06,605 ERROR cat].[localhost].[/].[dispatcherServlet]: 175 - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [org.apache.shiro.authc.AuthenticationException: Authentication failed for token submission [io.dataease.auth.entity.JWTToken@4fc87d3a].  Possible unexpected error? (Typical or expected login exceptions should extend from AuthenticationException).] with root cause
com.auth0.jwt.exceptions.TokenExpiredException: The Token has expired on Thu Jun 29 19:34:15 CST 2023.
        at com.auth0.jwt.JWTVerifier.assertDateIsFuture(JWTVerifier.java:403)
        at com.auth0.jwt.JWTVerifier.assertValidDateClaim(JWTVerifier.java:394)
        at com.auth0.jwt.JWTVerifier.verifyClaimValues(JWTVerifier.java:314)
        at com.auth0.jwt.JWTVerifier.verifyClaims(JWTVerifier.java:303)
        at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:288)
        at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:271)
        at io.dataease.auth.util.JWTUtils.verify(JWTUtils.java:46)
        at io.dataease.auth.config.F2CRealm.doGetAuthenticationInfo(F2CRealm.java:107)
        at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:571)
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doSingleRealmAuthentication(ModularRealmAuthenticator.java:180)
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:273)
        at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198)
        at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106)
        at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:275)
        at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:260)
        at io.dataease.auth.filter.JWTFilter.executeLogin(JWTFilter.java:80)
        at org.apache.shiro.web.filter.authc.HttpAuthenticationFilter.onAccessDenied(HttpAuthenticationFilter.java:230)
        at org.apache.shiro.web.filter.AccessControlFilter.onAccessDenied(AccessControlFilter.java:133)
        at org.apache.shiro.web.filter.AccessControlFilter.onPreHandle(AccessControlFilter.java:162)
        at org.apache.shiro.web.filter.PathMatchingFilter.isFilterChainContinued(PathMatchingFilter.java:223)
        at org.apache.shiro.web.filter.PathMatchingFilter.preHandle(PathMatchingFilter.java:198)
        at io.dataease.auth.filter.JWTFilter.preHandle(JWTFilter.java:127)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:131)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)^C

**Comment by BreadmanCheray** [comment]
2023-07-02 10:58:00,198 DEBUG er.SystemParameterMapper.selectByExample: 137 - ==>  Preparing: select param_key, param_value, type, sort from system_parameter WHERE ( param_key like ? )
2023-07-02 10:58:00,199 DEBUG er.SystemParameterMapper.selectByExample: 137 - ==> Parameters: ui%(String)
2023-07-02 10:58:00,201 DEBUG er.SystemParameterMapper.selectByExample: 137 - <==      Total: 14
2023-07-02 10:58:00,206 DEBUG er.FileMetadataMapper.selectByPrimaryKey: 137 - ==>  Preparing: select id, name, type, create_time, update_time, size from file_metadata where id = ?
2023-07-02 10:58:00,206 DEBUG er.FileMetadataMapper.selectByPrimaryKey: 137 - ==> Parameters: null
2023-07-02 10:58:00,209 DEBUG er.FileMetadataMapper.selectByPrimaryKey: 137 - <==      Total: 0
2023-07-02 10:58:00,216  WARN apache.shiro.authc.AbstractAuthenticator: 216 - Authentication failed for token submission [io.dataease.auth.entity.JWTToken@3f3edb04].  Possible unexpected error? (Typical or expected login exceptions should extend from AuthenticationException).
com.auth0.jwt.exceptions.TokenExpiredException: The Token has expired on Thu Jun 29 19:34:15 CST 2023.
        at com.auth0.jwt.JWTVerifier.assertDateIsFuture(JWTVerifier.java:403)
        at com.auth0.jwt.JWTVerifier.assertValidDateClaim(JWTVerifier.java:394)
        at com.auth0.jwt.JWTVerifier.verifyClaimValues(JWTVerifier.java:314)
        at com.auth0.jwt.JWTVerifier.verifyClaims(JWTVerifier.java:303)
        at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:288)
        at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:271)
        at io.dataease.auth.util.JWTUtils.verify(JWTUtils.java:46)
        at io.dataease.auth.config.F2CRealm.doGetAuthenticationInfo(F2CRealm.java:107)
        at org.apache.shiro.realm.AuthenticatingRealm.getAuthenticationInfo(AuthenticatingRealm.java:571)
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doSingleRealmAuthentication(ModularRealmAuthenticator.java:180)
        at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:273)
        at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198)
        at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106)
        at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:275)
        at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:260)
        at io.dataease.auth.filter.JWTFilter.executeLogin(JWTFilter.java:80)
        at io.dataease.auth.filter.JWTFilter.isAccessAllowed(JWTFilter.java:95)
        at org.apache.shiro.web.filter.AccessControlFilter.onPreHandle(AccessControlFilter.java:162)
        at org.apache.shiro.web.filter.PathMatchingFilter.isFilterChainContinued(PathMatchingFilter.java:223)
        at org.apache.shiro.web.filter.PathMatchingFilter.preHandle(PathMatchingFilter.java:198)
        at io.dataease.auth.filter.JWTFilter.preHandle(JWTFilter.java:127)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:131)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at io.dataease.commons.filter.SqlFilter.doFilter(SqlFilter.java:69)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:750)

**Comment by BreadmanCheray** [comment]
> 感谢反馈，目前测试环境没有发现你说的这个问题，方便看一下后台的日志吗

日志已经导出来，请帮忙查看一下，谢谢

**Comment by BBchicken-9527** [comment]
额...  你改动了源码了呀，不好意思哈，由于你对源码进行了改造我这边是没办法准确定位到你问题的原因，帮不到你不好意思哈；

**Comment by BreadmanCheray** [comment]
> 额... 你改动了源码了呀，不好意思哈，由于你对源码进行了改造我这边是没办法准确定位到你问题的原因，帮不到你不好意思哈；
我都没有改动源码，我是直接从旧版本升级新版本就出现这个问题。

**Comment by BBchicken-9527** [comment]
嗯... 好的，我们讨论一下；

**Comment by BreadmanCheray** [comment]
请问这个在最新版本解决了吗？

**Comment by BreadmanCheray** [comment]
> 嗯... 好的，我们讨论一下；


你好，请问这个问题是不是能在新版本中解决哈？
