### ISSUE TITLE
[Question] 全新安装 启动失败

### ISSUE THREAD

**Issue by poal222** [dataease/dataease#5646]
**请描述您的问题.**
1、使用离线安装包安装，按照官方教程
2、参照官方修改服务端口的教程，将80端口修改为8081，启动后，报错，数组越界

2023-07-13 09:32:42,148 DEBUG pper.DatasourceMapper.selectByPrimaryKey: 137 - <==      Total: 1
2023-07-13 09:32:42,177 ERROR g.springframework.boot.SpringApplication: 856 - Application run failed
java.lang.ArrayIndexOutOfBoundsException: 1
        at io.dataease.service.datasource.DatasourceService.updateDemoDs(DatasourceService.java:665)
        at io.dataease.service.datasource.DatasourceService$$FastClassBySpringCGLIB$$2ccad08e.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)

**Comment by yayanpei-fit2cloud** [comment]
是不是修改了原始数据库？可以把数据库删掉重建，然后重启试下。

**Comment by poal222** [comment]
> 是不是修改了原始数据库？可以把数据库删掉重建，然后重启试下。

 mysql直接是安装的时候默认docker下载的，我进去后把数据库删了，用文档里面的建库命令弄得，重启后，它自动执行初始化，但是也是一样，下图是info.log里面记录的出错信息
![image](https://github.com/dataease/dataease/assets/13061372/47267fdd-ec77-4cb4-ba8b-629f387fe8a7)
![image](https://github.com/dataease/dataease/assets/13061372/49d595e4-0595-4601-a071-5245ec374f76)
