### ISSUE TITLE
[Bug]创建 MaxCompute 关联数据集，保存报错

### ISSUE THREAD

**Issue by aliank516** [dataease/dataease#5791]
**DataEase 版本**
 `v1.18.9`

**运行方式**
`在线安装运行`

**浏览器版本**
`Microsoft Edge 最新`

**Bug 描述**
创建 MaxCompute 关联数据集，保存报错。
后台报错日志如下：
```shell
2023-07-28 16:28:39,883 [http-nio-8081-exec-10] ERROR i.d.c.handler.GlobalExceptionHandler 53 - Fail to proceed /dataset/table/update
io.dataease.plugins.common.exception.DataEaseException: java.sql.SQLException: Fail to run sql:SELECT * FROM (SELECT "dim_scm_nmpa_cosmetic"."cosmetic_id" AS f_89d423ca7c2bbf51,"dim_scm_nmpa_cosmetic"."product_name" AS f_3698c3e98e082cc1,"dim_scm_nmpa_cosmetic_nlp_tag"."brand_name" AS f_1d796ce3db409b59,"dim_scm_nmpa_cosmetic_nlp_tag"."first_category_name" AS f_fc672cb7ab7de365 FROM "dim_scm_nmpa_cosmetic"  LEFT JOIN  "dim_scm_nmpa_cosmetic_nlp_tag" ON "dim_scm_nmpa_cosmetic"."cosmetic_id" = "dim_scm_nmpa_cosmetic_nlp_tag"."cosmetic_id") AS tmp    LIMIT 1000 offset 0;, Error:[400] com.aliyun.odps.OdpsException: ODPS-0130161:[1,47] Parse exception - invalid token '"cosmetic_id"', expect one of ''.'','['
ODPS-0130161:[1,61] Parse exception - invalid token 'AS'
ODPS-0130161:[1,82] Parse exception - invalid token ',', expect one of 'UNION','SEMICOLON','MINUS','INTERSECT','EXCEPT'
ODPS-0130161:[1,292] Parse exception - invalid token '"dim_scm_nmpa_cosmetic"'
ODPS-0130161:[1,328] Parse exception - invalid token '"dim_scm_nmpa_cosmetic_nlp_tag"'
	at io.dataease.plugins.common.exception.DataEaseException.throwException(DataEaseException.java:22)
	at io.dataease.plugins.datasource.provider.DefaultJdbcProvider.fetchResultField(DefaultJdbcProvider.java:173)
	at io.dataease.service.dataset.DataSetTableService.saveTableField(DataSetTableService.java:2059)
	at io.dataease.service.dataset.DataSetTableService.save(DataSetTableService.java:349)
	at io.dataease.service.dataset.DataSetTableService$$FastClassBySpringCGLIB$$f5e098a2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at io.dataease.service.dataset.DataSetTableService$$EnhancerBySpringCGLIB$$804294db.save(<generated>)
	at io.dataease.service.dataset.DataSetTableService$$FastClassBySpringCGLIB$$f5e098a2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at io.dataease.service.dataset.DataSetTableService$$EnhancerBySpringCGLIB$$54743522.save(<generated>)
	at io.dataease.controller.dataset.DataSetTableController.save(DataSetTableController.java:80)
	at io.dataease.controller.dataset.DataSetTableController$$FastClassBySpringCGLIB$$5e61436c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
	at io.dataease.auth.aop.DePermissionAnnotationHandler.PermissionsAround(DePermissionAnnotationHandler.java:39)
	at jdk.internal.reflect.GeneratedMethodAccessor703.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at io.dataease.controller.dataset.DataSetTableController$$EnhancerBySpringCGLIB$$bafd52d0.save(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at io.dataease.commons.filter.SqlFilter.doFilter(SqlFilter.java:69)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLException: Fail to run sql:SELECT * FROM (SELECT "dim_scm_nmpa_cosmetic"."cosmetic_id" AS f_89d423ca7c2bbf51,"dim_scm_nmpa_cosmetic"."product_name" AS f_3698c3e98e082cc1,"dim_scm_nmpa_cosmetic_nlp_tag"."brand_name" AS f_1d796ce3db409b59,"dim_scm_nmpa_cosmetic_nlp_tag"."first_category_name" AS f_fc672cb7ab7de365 FROM "dim_scm_nmpa_cosmetic"  LEFT JOIN  "dim_scm_nmpa_cosmetic_nlp_tag" ON "dim_scm_nmpa_cosmetic"."cosmetic_id" = "dim_scm_nmpa_cosmetic_nlp_tag"."cosmetic_id") AS tmp    LIMIT 1000 offset 0;, Error:[400] com.aliyun.odps.OdpsException: ODPS-0130161:[1,47] Parse exception - invalid token '"cosmetic_id"', expect one of ''.'','['
ODPS-0130161:[1,61] Parse exception - invalid token 'AS'
ODPS-0130161:[1,82] Parse exception - invalid token ',', expect one of 'UNION','SEMICOLON','MINUS','INTERSECT','EXCEPT'
ODPS-0130161:[1,292] Parse exception - invalid token '"dim_scm_nmpa_cosmetic"'
ODPS-0130161:[1,328] Parse exception - invalid token '"dim_scm_nmpa_cosmetic_nlp_tag"'
	at com.aliyun.odps.jdbc.OdpsStatement.runSQL(OdpsStatement.java:985)
	at com.aliyun.odps.jdbc.OdpsStatement.executeQuery(OdpsStatement.java:353)
	at io.dataease.plugins.datasource.provider.DefaultJdbcProvider.fetchResultField(DefaultJdbcProvider.java:170)
	... 132 common frames omitted
Caused by: com.aliyun.odps.OdpsException: ODPS-0130161:[1,47] Parse exception - invalid token '"cosmetic_id"', expect one of ''.'','['
ODPS-0130161:[1,61] Parse exception - invalid token 'AS'
ODPS-0130161:[1,82] Parse exception - invalid token ',', expect one of 'UNION','SEMICOLON','MINUS','INTERSECT','EXCEPT'
ODPS-0130161:[1,292] Parse exception - invalid token '"dim_scm_nmpa_cosmetic"'
ODPS-0130161:[1,328] Parse exception - invalid token '"dim_scm_nmpa_cosmetic_nlp_tag"'
	at com.aliyun.odps.rest.RestClient.handleErrorResponse(RestClient.java:395)
	at com.aliyun.odps.rest.RestClient.request(RestClient.java:330)
	at com.aliyun.odps.rest.RestClient.request(RestClient.java:286)
	at com.aliyun.odps.rest.RestClient.stringRequest(RestClient.java:262)
	at com.aliyun.odps.Instances.create(Instances.java:395)
	at com.aliyun.odps.Instances.create(Instances.java:328)
	at com.aliyun.odps.Instances.create(Instances.java:293)
	at com.aliyun.odps.Instances.create(Instances.java:240)
	at com.aliyun.odps.task.SQLTask.run(SQLTask.java:640)
	at com.aliyun.odps.task.SQLTask.run(SQLTask.java:647)
	at com.aliyun.odps.task.SQLTask.run(SQLTask.java:576)
	at com.aliyun.odps.jdbc.OdpsStatement.runSQLOffline(OdpsStatement.java:840)
	at com.aliyun.odps.jdbc.OdpsStatement.runSQL(OdpsStatement.java:978)
	... 134 common frames omitted
Caused by: com.aliyun.odps.rest.RestException: RequestId=64C37C3754CF64A7EE9F81E3,Code=ParseError,Message=ODPS-0130161:[1,47] Parse exception - invalid token '"cosmetic_id"', expect one of ''.'','['
ODPS-0130161:[1,61] Parse exception - invalid token 'AS'
ODPS-0130161:[1,82] Parse exception - invalid token ',', expect one of 'UNION','SEMICOLON','MINUS','INTERSECT','EXCEPT'
ODPS-0130161:[1,292] Parse exception - invalid token '"dim_scm_nmpa_cosmetic"'
ODPS-0130161:[1,328] Parse exception - invalid token '"dim_scm_nmpa_cosmetic_nlp_tag"'
	... 147 common frames omitted

``` 

**Bug 重现步骤(有截图更好)**
1. 创建两张单表直连 MaxCompute 数据集。
2. 创建关联数据集，保存报错。
![image](https://github.com/dataease/dataease/assets/16068781/30deb518-fec1-4725-812f-592c0bf5a713)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复；
