### ISSUE TITLE
自定义datasource插件NoClassDefFoundError

### ISSUE THREAD

**Issue by cuishang544564** [dataease/dataease#6201]
**请描述您的问题.**
根据官方文档开发了tdengine的数据源插件打包后本地windows部署的dataease上传插件后可以正常使用
但在linux里driver报错
![image](https://github.com/dataease/dataease/assets/25947985/ed80bdd7-6271-4f4e-8a6c-6b10eea2386f)
java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSONObject
        at com.taosdata.jdbc.TSDBJNIConnector.init(TSDBJNIConnector.java:37)
        at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:162)
        at io.dataease.plugins.datasource.tdengine.provider.TdengineDsProvider.getConnection(TdengineDsProvider.java:53)
        at io.dataease.plugins.datasource.tdengine.provider.TdengineDsProvider.template(TdengineDsProvider.java:133)
        at io.dataease.plugins.datasource.tdengine.provider.TdengineDsProvider.checkStatus(TdengineDsProvider.java:126)
        at io.dataease.service.datasource.DatasourceService.validate(DatasourceService.java:334)

但在driver包里已经引入了fastjson的pom
![image](https://github.com/dataease/dataease/assets/25947985/1d7cea84-c5ff-4da9-bb9f-eed880aa16d7)
本地环境java_home是1.8，然后在idea里指定的jdk11
linux环境java_home是1.8，./jdk-11.0.19/bin/java -jar backend-1.18.10.jar 通过jdk11中的java命令启动
请问是什么原因导致的，跟java_home配置有关系吗

**Comment by xuwei-fit2cloud** [comment]
看着应该是jre环境问题，可以尝试重新配置一下java环境。
