### ISSUE TITLE
[Bug]预览 doris 数据集报错

### ISSUE THREAD

**Issue by moody1117** [dataease/dataease#6212]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
![image](https://github.com/dataease/dataease/assets/50506546/c610fd83-4683-4762-ac70-8deddc0081ee)

**Bug 描述**
新增 doris 数据源及数据集没有问题，但预览 doris数据时报错：预览数据错误：执行SQL失败。可能因相关字段、表、数据集等元素发生变更，请检查->SQL ERRORerrCode = 2, detailMessage = Invalid decimal type with precision = 20, scale = 0

**Bug 重现步骤(有截图更好)**
1.![image](https://github.com/dataease/dataease/assets/50506546/39eafa46-3b36-40c8-a6a0-f5a2c5f2bcc9)

2.![image](https://github.com/dataease/dataease/assets/50506546/22adfe5f-3a0f-4f72-bc8a-b04435b1688d)

3.![image](https://github.com/dataease/dataease/assets/50506546/8db81b18-90d6-4cc0-b3c2-f3cdb12cfc7b)

**Comment by moody1117** [comment]
CREATE TABLE sales_order
(
    orderid     INT,
    status      INT,
    username    VARCHAR(32),
    amount      INT 
)
UNIQUE KEY(orderid)
DISTRIBUTED BY HASH(orderid) BUCKETS 10
PROPERTIES (
    "replication_num" = "1"
);

insert into sales_order values(1001,1,'caolv',1500),(1002,2,'aqing',2000),(1003,3,'hema',2500),(1004,4,'haha',3000),(1005,5,'haha',3000);
建表语句及数据

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。
![image](https://github.com/dataease/dataease/assets/84372766/85aec8f4-e246-4a66-8e01-92281ef27112)

**Comment by moody1117** [comment]
预览 doris（apache/doris:2.0.0_alpha-fe-x86_64） 表的报错信息：
2023-09-26 10:06:53,231 DEBUG ease.ext.ExtDataSetTableMapper.searchOne: 137 - ==>  Preparing: select id, `name`, scene_id, data_source_id, `type`, `mode`,`info`, create_by, create_time, ( SELECT nick_name FROM sys_user WHERE sys_user.username = dataset_table.create_by ) AS creator_name, get_auths(id,'dataset',?) as `privileges`, scene_id as pid, sql_variable_details from dataset_table WHERE id = ?
2023-09-26 10:06:53,233 DEBUG ease.ext.ExtDataSetTableMapper.searchOne: 137 - ==> Parameters: 1(String), f7aee29f-a56a-437e-8aad-3ae98e40a0e1(String)
2023-09-26 10:06:53,235 DEBUG ease.ext.ExtDataSetTableMapper.searchOne: 137 - <==      Total: 1
2023-09-26 10:06:53,279 DEBUG ext.ExtDataSetTableMapper.findOneDetails: 137 - ==>  Preparing: select id, `name`, scene_id, data_source_id, `type`, `mode`, `info`, create_by, create_time, (SELECT nick_name FROM sys_user WHERE sys_user.username = dataset_table.create_by) AS creator_name from dataset_table where id = ?
2023-09-26 10:06:53,280 DEBUG .DatasetTableFieldMapper.selectByExample: 137 - ==>  Preparing: select id, table_id, origin_name, `name`, dataease_name, group_type, `type`, `size`, de_type, de_type_format, de_extract_type, ext_field, `checked`, column_index, last_sync_time, accuracy, date_format, date_format_type from dataset_table_field WHERE ( table_id = ? and `checked` = ? ) order by column_index asc
2023-09-26 10:06:53,281 DEBUG ext.ExtDataSetTableMapper.findOneDetails: 137 - ==> Parameters: f7aee29f-a56a-437e-8aad-3ae98e40a0e1(String)
2023-09-26 10:06:53,282 DEBUG .DatasetTableFieldMapper.selectByExample: 137 - ==> Parameters: f7aee29f-a56a-437e-8aad-3ae98e40a0e1(String), true(Boolean)
2023-09-26 10:06:53,283 DEBUG ext.ExtDataSetTableMapper.findOneDetails: 137 - <==      Total: 1
2023-09-26 10:06:53,284 DEBUG pper.DatasourceMapper.selectByPrimaryKey: 137 - ==>  Preparing: select id, `name`, `desc`, `type`, create_time, update_time, create_by, `status` , configuration from datasource where id = ?
2023-09-26 10:06:53,285 DEBUG pper.DatasourceMapper.selectByPrimaryKey: 137 - ==> Parameters: d29f4853-2abe-4c73-87ce-6493d6fc0226(String)
2023-09-26 10:06:53,286 DEBUG .DatasetTableFieldMapper.selectByExample: 137 - <==      Total: 3
2023-09-26 10:06:53,287 DEBUG pper.DatasourceMapper.selectByPrimaryKey: 137 - <==      Total: 1
2023-09-26 10:06:53,288 DEBUG er.DatasetTableMapper.selectByPrimaryKey: 137 - ==>  Preparing: select id, `name`, scene_id, data_source_id, `type`, `mode`, info, create_by, create_time, qrtz_instance, sync_status, last_update_time, sql_variable_details from dataset_table where id = ?
2023-09-26 10:06:53,289 DEBUG er.DatasetTableMapper.selectByPrimaryKey: 137 - ==> Parameters: f7aee29f-a56a-437e-8aad-3ae98e40a0e1(String)
2023-09-26 10:06:53,291 DEBUG er.DatasetTableMapper.selectByPrimaryKey: 137 - <==      Total: 1
2023-09-26 10:06:53,293 DEBUG pper.DatasourceMapper.selectByPrimaryKey: 137 - ==>  Preparing: select id, `name`, `desc`, `type`, create_time, update_time, create_by, `status` , configuration from datasource where id = ?
2023-09-26 10:06:53,294 DEBUG pper.DatasourceMapper.selectByPrimaryKey: 137 - ==> Parameters: d29f4853-2abe-4c73-87ce-6493d6fc0226(String)
2023-09-26 10:06:53,295 DEBUG pper.DatasourceMapper.selectByPrimaryKey: 137 - <==      Total: 1
2023-09-26 10:06:53,307 ERROR cat].[localhost].[/].[dispatcherServlet]: 175 - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.dataease.commons.exception.DEException: 预览数据错误：执行SQL失败。可能因相关字段、表、数据集等元素发生变更，请检查->SQL ERRORerrCode = 2, detailMessage = Invalid decimal type with precision = 20, scale = 0] with root cause
io.dataease.commons.exception.DEException: 预览数据错误：执行SQL失败。可能因相关字段、表、数据集等元素发生变更，请检查->SQL ERRORerrCode = 2, detailMessage = Invalid decimal type with precision = 20, scale = 0
        at io.dataease.commons.exception.DEException.throwException(DEException.java:14)
        at io.dataease.service.dataset.DataSetTableService.getPreviewData(DataSetTableService.java:641)
        at io.dataease.service.dataset.DataSetTableService$$FastClassBySpringCGLIB$$f5e098a2.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at io.dataease.service.dataset.DataSetTableService$$EnhancerBySpringCGLIB$$6caf0753.getPreviewData(<generated>)
        at io.dataease.service.dataset.DataSetTableService$$FastClassBySpringCGLIB$$f5e098a2.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at io.dataease.service.dataset.DataSetTableService$$EnhancerBySpringCGLIB$$c58d7ef4.getPreviewData(<generated>)
        at io.dataease.controller.dataset.DataSetTableController.getPreviewData(DataSetTableController.java:153)
        at io.dataease.controller.dataset.DataSetTableController$$FastClassBySpringCGLIB$$5e61436c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
        at io.dataease.auth.aop.DePermissionAnnotationHandler.PermissionAround(DePermissionAnnotationHandler.java:85)
        at sun.reflect.GeneratedMethodAccessor723.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at io.dataease.controller.dataset.DataSetTableController$$EnhancerBySpringCGLIB$$d33d0695.getPreviewData(<generated>)
        at sun.reflect.GeneratedMethodAccessor1161.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at io.dataease.commons.filter.SqlFilter.doFilter(SqlFilter.java:69)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:750

**Comment by BBchicken-9527** [comment]
嗯.... 你这个table变更过字段嘛？受累看一下字段管理字段信息对的上吗？

**Comment by moody1117** [comment]
重新建了一张表，1.18.8 到最新的 dataease 版本之间有更改读取 doris 数据的逻辑吗？ 你用的 doris 是什么版本的？
drop table test;
CREATE TABLE test
(
    id     INT,
    name   VARCHAR(255),
    age    VARCHAR(255)
)
UNIQUE KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 10
PROPERTIES (
    "replication_num" = "1"
);
![image](https://github.com/dataease/dataease/assets/50506546/919aff06-349b-44d9-b8aa-49bf6d4bbff5)


select * from test;

insert into test values(1001,'caolv','男'),(1002,'hihi','男'),(1003,'peter','男'),(1004,'juice','女');

![image](https://github.com/dataease/dataease/assets/50506546/17c31da9-7b99-453d-8e88-721de8558f90)

![image](https://github.com/dataease/dataease/assets/50506546/2d25f703-f8d3-4cce-b39a-b5484161db6a)

**Comment by moody1117** [comment]
很奇怪，表里面都没有 decimal 类型的字段

**Comment by moody1117** [comment]
@BBchicken-9527 装了最新版的 Dataease1.18.11,读取时同样报错
![image](https://github.com/dataease/dataease/assets/50506546/b7b5f256-603b-465c-b773-d327091f0613)

![image](https://github.com/dataease/dataease/assets/50506546/4b74be00-b203-479a-ba90-6848d659f867)

**Comment by BBchicken-9527** [comment]
我看你这里是直连的，我们是直接通过sql去你所在库进行查询的，所以理论上不会改变你数据库的字段类型，你看看同步字段之后是否能正常呢？

**Comment by moody1117** [comment]
应该是 doris 版本问题， 换成 1.2.1的就可以了

**Comment by BBchicken-9527** [comment]
😂没有同步是吗，那如果没有其他问题我将关闭这个问题；

**Comment by moody1117** [comment]
好的，关闭吧。

**Comment by gitfortian** [comment]
我也遇到了  还解决  doris2.0.1 查询数值类的列 报错
