### ISSUE TITLE
1.18.12 启动失败问题

### ISSUE THREAD

**Issue by larryyoung60** [dataease/dataease#6818]
**请描述您的问题.**
编译成功，启动失败

版本为1.18.12

失败日志
2023-11-23 16:55:53,309  INFO tuate.endpoint.web.EndpointLinksResolver:  58 - Exposing 2 endpoint(s) beneath base path '/actuator'
2023-11-23 16:55:53,559  INFO duling.concurrent.ThreadPoolTaskExecutor: 181 - Initializing ExecutorService 'taskExecutor'
2023-11-23 16:55:54,031  WARN ConfigServletWebServerApplicationContext: 590 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kettleFileRepository' defined in class path resource [io/dataease/config/CommonConfig.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.pentaho.di.repository.AbstractRepository] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@14acaea5]
2023-11-23 16:55:54,032  INFO duling.concurrent.ThreadPoolTaskExecutor: 218 - Shutting down ExecutorService 'taskExecutor'
2023-11-23 16:55:54,069  INFO duling.concurrent.ThreadPoolTaskExecutor: 218 - Shutting down ExecutorService 'brokerChannelExecutor'
2023-11-23 16:55:54,070  INFO duling.concurrent.ThreadPoolTaskExecutor: 218 - Shutting down ExecutorService 'clientOutboundChannelExecutor'
2023-11-23 16:55:54,072  INFO duling.concurrent.ThreadPoolTaskExecutor: 218 - Shutting down ExecutorService 'clientInboundChannelExecutor'
2023-11-23 16:55:54,077  INFO k.scheduling.quartz.SchedulerFactoryBean: 845 - Shutting down Quartz Scheduler
2023-11-23 16:55:54,077  INFO          org.quartz.core.QuartzScheduler: 666 - Scheduler clusterScheduler_$_LAPTOP-8R1VHEHR1700729747542 shutting down.
2023-11-23 16:55:54,077  INFO          org.quartz.core.QuartzScheduler: 585 - Scheduler clusterScheduler_$_LAPTOP-8R1VHEHR1700729747542 paused.
2023-11-23 16:55:54,081  INFO          org.quartz.core.QuartzScheduler: 740 - Scheduler clusterScheduler_$_LAPTOP-8R1VHEHR1700729747542 shutdown complete.
2023-11-23 16:55:54,085  INFO       com.zaxxer.hikari.HikariDataSource: 350 - DatebookHikariCP - Shutdown initiated...
2023-11-23 16:55:54,097  INFO       com.zaxxer.hikari.HikariDataSource: 352 - DatebookHikariCP - Shutdown completed.
2023-11-23 16:55:54,100  INFO org.apache.catalina.core.StandardService: 173 - Stopping service [Tomcat]
2023-11-23 16:55:54,111  INFO ConditionEvaluationReportLoggingListener: 136 -

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-11-23 16:55:54,128 ERROR g.springframework.boot.SpringApplication: 856 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kettleFileRepository' defined in class path resource [io/dataease/config/CommonConfig.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.pentaho.di.repository.AbstractRepository] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@14acaea5]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:579)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
        at io.dataease.Application.main(Application.java:22)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.pentaho.di.repository.AbstractRepository] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@14acaea5]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481)
        at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.buildLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:232)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.findLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:210)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(InitDestroyAnnotationBeanPostProcessor.java:149)
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(CommonAnnotationBeanPostProcessor.java:294)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:1098)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
        ... 24 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/pentaho/platform/api/repository2/unified/IUnifiedRepository
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2310)
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463)
        ... 31 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.pentaho.platform.api.repository2.unified.IUnifiedRepository
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 35 common frames omitted

**Comment by xuwei-fit2cloud** [comment]
源码运行没有发现上述问题，请确认一下是否有修改kettle相关依赖的版本，或者尝试重新下载一下kettle相关依赖。
