### ISSUE TITLE
无法编译v1.18.12版本分支源代码

### ISSUE THREAD

**Issue by 804e** [dataease/dataease#7152]
**DataEase 版本**
v1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
windows/chrome

**Bug 描述**
无法编译模块view-sankey-frontend,  报错`TypeError: route is not a function`

**Bug 重现步骤(有截图更好)**
1. 使用命令`mvn clean package -X -rf :view-sankey-frontend`进行编译
2. 命令报错
```
[INFO] Running 'npm run buildPlugin' in E:\develop\code\example\dataease\extensions\dataease-extensions-view\view-sankey\view-sankey-frontend
[DEBUG] Executing command line [E:\develop\code\example\dataease\extensions\dataease-extensions-view\view-sankey\view-sankey-frontend\node\node.exe, E:\develop\code\example\dataease\extensions\dataease-extensions-view\view-sankey\view-sankey-frontend\node\node_modules\npm\bin\npm-cli.js, run, buildPlugin]
[INFO]
[INFO] > deplugin-view-frontend@1.0.0 buildPlugin
[INFO] > node build/build-async-plugins.js
[INFO]
[INFO] E:\develop\code\example\dataease\extensions\dataease-extensions-view\view-sankey\view-sankey-frontend\node_modules\color-convert\index.js:67
[INFO]  var routes = route(fromModel);
[INFO]               ^
[INFO]
[INFO] TypeError: route is not a function
[INFO]     at E:\develop\code\example\dataease\extensions\dataease-extensions-view\view-sankey\view-sankey-frontend\node_modules\color-convert\index.js:67:15
[INFO]     at Array.forEach (<anonymous>)
[INFO]     at Object.<anonymous> (E:\develop\code\example\dataease\extensions\dataease-extensions-view\view-sankey\view-sankey-frontend\node_modules\color-convert\index.js:61:8)
[INFO]     at Module._compile (node:internal/modules/cjs/loader:1198:14)
[INFO]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
[INFO]     at Module.load (node:internal/modules/cjs/loader:1076:32)
[INFO]     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
[INFO]     at Module.require (node:internal/modules/cjs/loader:1100:19)
[INFO]     at require (node:internal/modules/cjs/helpers:119:18)
[INFO]     at Object.<anonymous> (E:\develop\code\example\dataease\extensions\dataease-extensions-view\view-sankey\view-sankey-frontend\node_modules\ansi-styles\index.js:2:22)
[INFO] npm ERR! code 1
[INFO] npm ERR! path E:\develop\code\example\dataease\extensions\dataease-extensions-view\view-sankey\view-sankey-frontend
[INFO] npm ERR! command failed
[INFO] npm ERR! command C:\windows\system32\cmd.exe /d /s /c node build/build-async-plugins.js
[INFO]
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     C:\Users\wangweifeng\AppData\Local\npm-cache\_logs\2023-12-14T02_54_46_891Z-debug.log
```
3. 日志文件`C:\Users\wangweifeng\AppData\Local\npm-cache\_logs\2023-12-14T02_54_46_891Z-debug.log`
```
0 verbose cli [
0 verbose cli   'E:\\develop\\code\\example\\dataease\\extensions\\dataease-extensions-view\\view-sankey\\view-sankey-frontend\\node\\node.exe',
0 verbose cli   'E:\\develop\\code\\example\\dataease\\extensions\\dataease-extensions-view\\view-sankey\\view-sankey-frontend\\node\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'buildPlugin'
0 verbose cli ]
1 info using npm@7.6.3
2 info using node@v16.20.2
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:E:\develop\code\example\dataease\extensions\dataease-extensions-view\view-sankey\view-sankey-frontend\node\node_modules\npm\npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:E:\develop\code\example\dataease\extensions\dataease-extensions-view\view-sankey\view-sankey-frontend\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\wangweifeng\.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:E:\develop\code\example\dataease\extensions\dataease-extensions-view\view-sankey\view-sankey-frontend\node\etc\npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 verbose npm-session 02f9d75e746260b5
20 timing npm:load Completed in 19ms
21 timing command:run Completed in 141ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (E:\develop\code\example\dataease\extensions\dataease-extensions-view\view-sankey\view-sankey-frontend\node\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:513:28)
22 verbose stack     at maybeClose (node:internal/child_process:1100:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
23 verbose pkgid deplugin-view-frontend@1.0.0
24 verbose cwd E:\develop\code\example\dataease\extensions\dataease-extensions-view\view-sankey\view-sankey-frontend
25 verbose Windows_NT 10.0.19045
26 verbose argv "E:\\develop\\code\\example\\dataease\\extensions\\dataease-extensions-view\\view-sankey\\view-sankey-frontend\\node\\node.exe" "E:\\develop\\code\\example\\dataease\\extensions\\dataease-extensions-view\\view-sankey\\view-sankey-frontend\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "buildPlugin"
27 verbose node v16.20.2
28 verbose npm  v7.6.3
29 error code 1
30 error path E:\develop\code\example\dataease\extensions\dataease-extensions-view\view-sankey\view-sankey-frontend
31 error command failed
32 error command C:\windows\system32\cmd.exe /d /s /c node build/build-async-plugins.js
33 verbose exit 1
```

**Comment by BBchicken-9527** [comment]
感谢反馈，由于你是源码运行，不确定你是否改动和以及打包方式都有可能存在问题，建议你加入我们的交流群，上面有非常专业的同学会实时的回复你的问题，方便你快速并精准的定位到你的问题所在；

**Comment by 804e** [comment]
单独在模块里面执行`npm install async`后解决了
