### ISSUE TITLE
[Bug]PostgreSql数据源，使用sql数据集定时同步异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#8777]
**DataEase 版本**
1.18.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
PostgreSql数据源，使用sql数据集定时同步异常
![wecom-temp-155555-60d956603cf0809a1b33e3eab37862bb](https://github.com/dataease/dataease/assets/89771514/4d9ea206-bf78-4e43-aa16-0d0a3a050185)

![wecom-temp-57272-21e066a214f175778d67a01e66d4ed94](https://github.com/dataease/dataease/assets/89771514/64534fd1-13cc-4d7a-b957-25fa52cd11b4)

异常日志中的sql，分析发现分页语法有问题：
<img width="1074" alt="image" src="https://github.com/dataease/dataease/assets/89771514/2a4770d9-ac60-4eb8-8da9-db897dc55f5a">

异常日志如下：
`#######################################################################
WARNING:  no libwebkitgtk-1.0 detected, some features will be unavailable
    Consider installing the package with apt-get or yum.
    e.g. 'sudo apt-get install libwebkitgtk-1.0-0'
#######################################################################
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
08:14:11,008 WARN  [KarafBoot] Karaf not found in standard dir of './system/karaf' 
08:14:11,022 ERROR [KarafBoot] Error starting Karaf
java.io.FileNotFoundException: Source './system/karaf' does not exist
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1298)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1240)
	at org.pentaho.platform.osgi.KarafBoot.startup(KarafBoot.java:191)
	at org.pentaho.di.osgi.registryExtension.OSGIPluginRegistryExtension.init(OSGIPluginRegistryExtension.java:109)
	at org.pentaho.di.core.plugins.PluginRegistry.init(PluginRegistry.java:565)
	at org.pentaho.di.core.plugins.PluginRegistry.init(PluginRegistry.java:545)
	at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:117)
	at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:80)
	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:133)
	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:100)
	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:81)
	at org.pentaho.di.www.Carte.setKettleEnvironment(Carte.java:241)
	at org.pentaho.di.www.Carte.parseAndRunCommand(Carte.java:234)
	at org.pentaho.di.www.Carte.main(Carte.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
log4j:ERROR Could not create an Appender. Reported error follows.
java.lang.ClassCastException: org.apache.log4j.ConsoleAppender cannot be cast to org.apache.log4j.Appender
	at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:248)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:176)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:191)
	at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:523)
	at org.apache.log4j.xml.DOMConfigurator.parseCategory(DOMConfigurator.java:436)
	at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:1004)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:872)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:755)
	at org.apache.log4j.xml.DOMConfigurator.configure(DOMConfigurator.java:896)
	at org.pentaho.di.core.logging.log4j.Log4jLogging.applyLog4jConfiguration(Log4jLogging.java:101)
	at org.pentaho.di.core.logging.log4j.Log4jLogging.createLogger(Log4jLogging.java:109)
	at org.pentaho.di.core.logging.log4j.Log4jLogging.init(Log4jLogging.java:71)
	at org.pentaho.di.core.KettleClientEnvironment.initLogginPlugins(KettleClientEnvironment.java:157)
	at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:120)
	at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:80)
	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:133)
	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:100)
	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:81)
	at org.pentaho.di.www.Carte.setKettleEnvironment(Carte.java:241)
	at org.pentaho.di.www.Carte.parseAndRunCommand(Carte.java:234)
	at org.pentaho.di.www.Carte.main(Carte.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
log4j:ERROR Could not create an Appender. Reported error follows.
java.lang.ClassCastException: org.apache.log4j.ConsoleAppender cannot be cast to org.apache.log4j.Appender
	at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:248)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:176)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:191)
	at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:523)
	at org.apache.log4j.xml.DOMConfigurator.parseRoot(DOMConfigurator.java:492)
	at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:1006)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:872)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:755)
	at org.apache.log4j.xml.DOMConfigurator.configure(DOMConfigurator.java:896)
	at org.pentaho.di.core.logging.log4j.Log4jLogging.applyLog4jConfiguration(Log4jLogging.java:101)
	at org.pentaho.di.core.logging.log4j.Log4jLogging.createLogger(Log4jLogging.java:109)
	at org.pentaho.di.core.logging.log4j.Log4jLogging.init(Log4jLogging.java:71)
	at org.pentaho.di.core.KettleClientEnvironment.initLogginPlugins(KettleClientEnvironment.java:157)
	at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:120)
	at org.pentaho.di.core.KettleClientEnvironment.init(KettleClientEnvironment.java:80)
	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:133)
	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:100)
	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:81)
	at org.pentaho.di.www.Carte.setKettleEnvironment(Carte.java:241)
	at org.pentaho.di.www.Carte.parseAndRunCommand(Carte.java:234)
	at org.pentaho.di.www.Carte.main(Carte.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
08:15:52,112 ERROR [KarafLifecycleListener] The Kettle Karaf Lifecycle Listener failed to execute properly after waiting for 100 seconds. Releasing lifecycle hold, but some services may be unavailable.
2024/03/28 08:15:52 - Carte - Installing timer to purge stale objects after 1440 minutes.
2024/03/28 08:15:52 - Carte - Created listener for webserver @ address : kettle:18080
2024/03/28 08:29:48 - RepositoriesMeta - Reading repositories XML file: /opt/dataease/conf/.kettle/repositories.xml
2024/03/28 08:29:48 - trans_ds_72ddd0ef_07a6_495b_803c_ee96bb71511c - Dispatching started for transformation [trans_ds_72ddd0ef_07a6_495b_803c_ee96bb71511c]
org.pentaho.di.core.exception.KettleStepException: 
Unable to get queryfields for SQL: 
SELECT "thisweek" AS C_91f6c9d70f17de836ac2a504de639f02,"machinename" AS C_62f2e1d94ea5a730c4dfda5ead0bde29,"生产时间" AS C_4c12f9b98c4562c5546d755a20c14f26,"开机率" AS C_d3a2d3fefe71d29ec2d15f65e9e8e0c6,"组织停机" AS C_7de5187fcb38a44dc518447fe4a4da3e,"组织停机率" AS C_09009a791cc7703155e5a729fa0743a5,"待机" AS C_6f5af718128cae9b42c69197d620b6a5,"待机率" AS C_6217c5eb83b7c8eb0acdab2ee0084fd1,"故障停机" AS C_4f1f313487acee1859f0ba72b409137b,"故障停机率" AS C_2e27124acbee421395ad3110f9ff2e01 FROM  (-- 传入日期,获取当日所在月的各种率
with 
T0 as (
select date_part('day' ,getqhjmonth('2024-03-01') - interval '1 day') as monthdays
),
T1 as 
(
select * from getjymacmonthstatus('2024-03-01')
--where machinename='55MN正'
)
select thisweek,machinename,
sum(
case when putoncontent in ('生产','试模','上下模') then usetime end
) as 生产时间,
100 * intervaltohour(
sum(
case when putoncontent in ('生产','试模','上下模') then usetime end
)
)/(T0.monthdays*24) as 开机率,
sum(
case when putoncontent in ('清筒','吹水','组织停机','清/换水嘴','清压余','冷床积料') then usetime end
) as 组织停机,
100 * intervaltohour(
sum(
case when putoncontent in ('清筒','吹水','组织停机','清/换水嘴','清压余','冷床积料') then usetime end
)
)/(T0.monthdays*24) as 组织停机率,
sum(
case when putoncontent in ('待机','计划检修') then usetime end
) as 待机,
100 * intervaltohour(
sum(
case when putoncontent in ('待机','计划检修')  then usetime end
)
)/(T0.monthdays*24) as 待机率,
sum(
case when putoncontent in ('故障停机','故障检修') then usetime end
) as 故障停机,
100 * intervaltohour(
sum(
case when putoncontent in ('故障停机','故障检修')  then usetime end
)
)/(T0.monthdays*24) as 故障停机率
from T1,T0
group by thisweek,machinename,T0.monthdays) AS DE_TEMP   LIMIT DE_PAGE_SIZE OFFSET DE_OFFSET 
Couldn't get field info from [SELECT "thisweek" AS C_91f6c9d70f17de836ac2a504de639f02,"machinename" AS C_62f2e1d94ea5a730c4dfda5ead0bde29,"生产时间" AS C_4c12f9b98c4562c5546d755a20c14f26,"开机率" AS C_d3a2d3fefe71d29ec2d15f65e9e8e0c6,"组织停机" AS C_7de5187fcb38a44dc518447fe4a4da3e,"组织停机率" AS C_09009a791cc7703155e5a729fa0743a5,"待机" AS C_6f5af718128cae9b42c69197d620b6a5,"待机率" AS C_6217c5eb83b7c8eb0acdab2ee0084fd1,"故障停机" AS C_4f1f313487acee1859f0ba72b409137b,"故障停机率" AS C_2e27124acbee421395ad3110f9ff2e01 FROM  (-- 传入日期,获取当日所在月的各种率
with 
T0 as (
select date_part('day' ,getqhjmonth('2024-03-01') - interval '1 day') as monthdays
),
T1 as 
(
select * from getjymacmonthstatus('2024-03-01')
--where machinename='55MN正'
)
select thisweek,machinename,
sum(
case when putoncontent in ('生产','试模','上下模') then usetime end
) as 生产时间,
100 * intervaltohour(
sum(
case when putoncontent in ('生产','试模','上下模') then usetime end
)
)/(T0.monthdays*24) as 开机率,
sum(
case when putoncontent in ('清筒','吹水','组织停机','清/换水嘴','清压余','冷床积料') then usetime end
) as 组织停机,
100 * intervaltohour(
sum(
case when putoncontent in ('清筒','吹水','组织停机','清/换水嘴','清压余','冷床积料') then usetime end
)
)/(T0.monthdays*24) as 组织停机率,
sum(
case when putoncontent in ('待机','计划检修') then usetime end
) as 待机,
100 * intervaltohour(
sum(
case when putoncontent in ('待机','计划检修')  then usetime end
)
)/(T0.monthdays*24) as 待机率,
sum(
case when putoncontent in ('故障停机','故障检修') then usetime end
) as 故障停机,
100 * intervaltohour(
sum(
case when putoncontent in ('故障停机','故障检修')  then usetime end
)
)/(T0.monthdays*24) as 故障停机率
from T1,T0
group by thisweek,machinename,T0.monthdays) AS DE_TEMP   LIMIT DE_PAGE_SIZE OFFSET DE_OFFSET ]
错误: 字段 "de_offset" 不存在
  Position: 1619
	at org.pentaho.di.trans.steps.tableinput.TableInputMeta.getFields(TableInputMeta.java:264)
	at org.pentaho.di.trans.TransMeta.getThisStepFields(TransMeta.java:2054)
	at org.pentaho.di.trans.TransMeta.getStepFields(TransMeta.java:1872)
	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1951)
	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1921)
	at org.pentaho.di.trans.TransMeta.getPrevStepFields(TransMeta.java:1904)
	at org.pentaho.di.trans.steps.userdefinedjavaclass.TransformClassBase.<init>(TransformClassBase.java:74)
	at Processor.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.pentaho.di.trans.steps.userdefinedjavaclass.UserDefinedJavaClassMeta.newChildInstance(UserDefinedJavaClassMeta.java:228)
	at org.pentaho.di.trans.steps.userdefinedjavaclass.UserDefinedJavaClass.<init>(UserDefinedJavaClass.java:63)
	at org.pentaho.di.trans.steps.userdefinedjavaclass.UserDefinedJavaClassMeta.getStep(UserDefinedJavaClassMeta.java:717)
	at org.pentaho.di.trans.Trans.prepareExecution(Trans.java:1032)
	at org.pentaho.di.www.PrepareExecutionTransServlet.doGet(PrepareExecutionTransServlet.java:218)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:575)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:522)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
	at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
Couldn't get field info from [SELECT "thisweek" AS C_91f6c9d70f17de836ac2a504de639f02,"machinename" AS C_62f2e1d94ea5a730c4dfda5ead0bde29,"生产时间" AS C_4c12f9b98c4562c5546d755a20c14f26,"开机率" AS C_d3a2d3fefe71d29ec2d15f65e9e8e0c6,"组织停机" AS C_7de5187fcb38a44dc518447fe4a4da3e,"组织停机率" AS C_09009a791cc7703155e5a729fa0743a5,"待机" AS C_6f5af718128cae9b42c69197d620b6a5,"待机率" AS C_6217c5eb83b7c8eb0acdab2ee0084fd1,"故障停机" AS C_4f1f313487acee1859f0ba72b409137b,"故障停机率" AS C_2e27124acbee421395ad3110f9ff2e01 FROM  (-- 传入日期,获取当日所在月的各种率
with 
T0 as (
select date_part('day' ,getqhjmonth('2024-03-01') - interval '1 day') as monthdays
),
T1 as 
(
select * from getjymacmonthstatus('2024-03-01')
--where machinename='55MN正'
)
select thisweek,machinename,
sum(
case when putoncontent in ('生产','试模','上下模') then usetime end
) as 生产时间,
100 * intervaltohour(
sum(
case when putoncontent in ('生产','试模','上下模') then usetime end
)
)/(T0.monthdays*24) as 开机率,
sum(
case when putoncontent in ('清筒','吹水','组织停机','清/换水嘴','清压余','冷床积料') then usetime end
) as 组织停机,
100 * intervaltohour(
sum(
case when putoncontent in ('清筒','吹水','组织停机','清/换水嘴','清压余','冷床积料') then usetime end
)
)/(T0.monthdays*24) as 组织停机率,
sum(
case when putoncontent in ('待机','计划检修') then usetime end
) as 待机,
100 * intervaltohour(
sum(
case when putoncontent in ('待机','计划检修')  then usetime end
)
)/(T0.monthdays*24) as 待机率,
sum(
case when putoncontent in ('故障停机','故障检修') then usetime end
) as 故障停机,
100 * intervaltohour(
sum(
case when putoncontent in ('故障停机','故障检修')  then usetime end
)
)/(T0.monthdays*24) as 故障停机率
`

**Comment by xuwei-fit2cloud** [comment]
问题已经修复，请等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
