### ISSUE TITLE
[Bug]更新到v1.18.17后，打开公共连接大约3分钟仪表板就报错

### ISSUE THREAD

**Issue by moncat2005** [dataease/dataease#8839]
**DataEase 版本**
1.18.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 123.0.6312.86

**Bug 描述**
今天下午从V1.18.15更新到v1.18.17后，浏览器的公共连接仪表板大约3分钟以上就报错。
java.lang.NullPointerException,无法正常显示如有疑问请联系管理员
重启BI系统重新打开公共链接依然如此

进一步确认，连管理员登陆BI后，查看仪表板也一样报错。

**Bug 重现步骤(有截图更好)**
![error-bi](https://github.com/dataease/dataease/assets/34859687/17a68c93-e873-4040-aff7-d258a4ab3bad)

**Comment by xuwei-fit2cloud** [comment]
麻烦您在出现报错的时候，看看服务器的后台日志。
日志文件所在目录：
/opt/dataease/logs/dataease

可以查看一下info.log文件里包含NullPointerException的信息发给我们。

**Comment by moncat2005** [comment]
进一步验证，降级到V1.18.16仍然如此，而且仪表板的36号以上的字号似乎与原来差异很大。
info.log相关报错信息如下：
![error-bi-2](https://github.com/dataease/dataease/assets/34859687/0cdeaca2-2943-4929-ac2b-9282260a970d)

**Comment by moncat2005** [comment]
早上重启dataease主机后，再次确认：5分钟后所有滚动显示的列表失效，饼图之类的还在。

**Comment by moncat2005** [comment]
早上重启dataease主机后，再次确认：5分钟后所有滚动显示的列表失效，饼图之类的还在。
这个错误应该和表格视图的刷新配置时间有关，之前V1.18.15的时候均为正常刷新和显示的。
整页面刷新恢复正常，但其中的表格视图自动刷新时间到了就报这个错误。
我设其中一个列表为3分钟，到了时间这个列表报错，同时其余列表的滚动变成停止了。

**Comment by xuwei-fit2cloud** [comment]
麻烦您帮忙截图一下包含完整NullPointerException错误堆栈信息的日志，仅仅grep出包含NullPointerException的部分，我们是无法定位具体代码的。谢谢。

**Comment by moncat2005** [comment]
![1](https://github.com/dataease/dataease/assets/34859687/f22fc38d-6156-4511-93df-0219c0868ae9)
![2](https://github.com/dataease/dataease/assets/34859687/8298fb04-2339-4227-a0ac-d873697d0650)
![3](https://github.com/dataease/dataease/assets/34859687/0e56edb9-9ab4-4b08-adff-114bde0a6618)
![4](https://github.com/dataease/dataease/assets/34859687/e36ee565-3c46-4b34-b622-5b39ff6af874)
![5](https://github.com/dataease/dataease/assets/34859687/087254eb-ad9f-4fa1-b039-dda3ff054e1d)
![6](https://github.com/dataease/dataease/assets/34859687/6246a0ce-af37-4fff-b80c-ddf8541654ac)

**Comment by moncat2005** [comment]
2024-04-01 13:12:46,650 [http-nio-8081-exec-32] ERROR i.d.service.chart.ChartViewService 139 - Method[cacheViewData][io.dataease.plugins.common.exception.DataEaseException: Data source connection exception: null]
2024-04-01 13:12:46,651 [http-nio-8081-exec-32] ERROR i.d.service.chart.ChartViewService 139 - Method[calcData][io.dataease.plugins.common.exception.DataEaseException: Data source connection exception: null]
2024-04-01 13:12:46,652 [http-nio-8081-exec-32] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] 175 - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.dataease.plugins.common.exception.DataEaseException: java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at io.dataease.plugins.common.request.datasource.DatasourceRequest.rebuildSqlWithFragment(DatasourceRequest.java:45)
	at io.dataease.plugins.common.request.datasource.DatasourceRequest.getQuery(DatasourceRequest.java:24)
	at io.dataease.service.chart.ChartViewService.calcData(ChartViewService.java:1528)
	at io.dataease.service.chart.ChartViewService.getData(ChartViewService.java:336)
	at io.dataease.service.chart.ChartViewService$$FastClassBySpringCGLIB$$62336a69.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at io.dataease.service.chart.ChartViewService$$EnhancerBySpringCGLIB$$4c168dfc.getData(<generated>)
	at io.dataease.service.chart.ChartViewService$$FastClassBySpringCGLIB$$62336a69.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at io.dataease.service.chart.ChartViewService$$EnhancerBySpringCGLIB$$8a9ef300.getData(<generated>)
	at io.dataease.controller.panel.server.LinkServer.viewDetail(LinkServer.java:121)
	at jdk.internal.reflect.GeneratedMethodAccessor941.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at io.dataease.commons.filter.HtmlResourceFilter.doFilter(HtmlResourceFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at io.dataease.commons.filter.SqlFilter.doFilter(SqlFilter.java:69)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
2024-04-01 13:12:46,654 [http-nio-8081-exec-32] ERROR i.d.c.handler.GlobalExceptionHandler 53 - Fail to proceed /api/link/viewDetail/f628c303-dab7-11ed-b793-c756fcaad2a0/f6055c5e-dab7-11ed-b793-c756fcaad2a0
io.dataease.plugins.common.exception.DataEaseException: java.lang.NullPointerException
	at io.dataease.plugins.common.exception.DataEaseException.throwException(DataEaseException.java:22)
	at io.dataease.service.chart.ChartViewService.getData(ChartViewService.java:341)
	at io.dataease.service.chart.ChartViewService$$FastClassBySpringCGLIB$$62336a69.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at io.dataease.service.chart.ChartViewService$$EnhancerBySpringCGLIB$$4c168dfc.getData(<generated>)
	at io.dataease.service.chart.ChartViewService$$FastClassBySpringCGLIB$$62336a69.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at io.dataease.service.chart.ChartViewService$$EnhancerBySpringCGLIB$$8a9ef300.getData(<generated>)
	at io.dataease.controller.panel.server.LinkServer.viewDetail(LinkServer.java:121)
	at jdk.internal.reflect.GeneratedMethodAccessor941.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at io.dataease.commons.filter.HtmlResourceFilter.doFilter(HtmlResourceFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at io.dataease.commons.filter.SqlFilter.doFilter(SqlFilter.java:69)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: null
	at io.dataease.plugins.common.request.datasource.DatasourceRequest.rebuildSqlWithFragment(DatasourceRequest.java:45)
	at io.dataease.plugins.common.request.datasource.DatasourceRequest.getQuery(DatasourceRequest.java:24)
	at io.dataease.service.chart.ChartViewService.calcData(ChartViewService.java:1528)
	at io.dataease.service.chart.ChartViewService.getData(ChartViewService.java:336)
	... 90 common frames omitted
2024-04-01 13:12:46,687 [http-nio-8081-exec-25] INFO  i.d.service.chart.ChartViewService ? - plugin_sql:SELECT
    *
FROM
    (SELECT
        CAST(t_a_0.`C_ba569b80f7bb7762f073f1be57cc36aa` AS CHAR) AS f_ax_5,
        CAST(t_a_0.`C_28c1e37e317b935a387dbe232bc9f803` AS CHAR) AS f_ax_6
        ,
        group_concat(t_a_0.`C_4236dde28b0d97ae6c5cc6730afeb04e`) AS f_ay_3,
        group_concat(t_a_0.`C_c3e99f0835b258f2a1735d7eae0be945`) AS f_ay_4,
        COUNT(*) AS f_ay_7
    FROM
        `ds_322094ca_6f7e_49a0_b126_0277f28987d3`   t_a_0
    GROUP BY
        CAST(t_a_0.`C_ba569b80f7bb7762f073f1be57cc36aa` AS CHAR),
        CAST(t_a_0.`C_28c1e37e317b935a387dbe232bc9f803` AS CHAR)
    )   t_a_1
 LIMIT 0,200

**Comment by moncat2005** [comment]
凡是表格滚动，只要选择表格数据刷新，配置刷新时间，到了刷新周期必定报错。
临时改成浏览器刷新对付着

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by tjlygdx** [comment]
> 凡是表格滚动，只要选择表格数据刷新，配置刷新时间，到了刷新周期必定报错。 临时改成浏览器刷新对付着

这个视图相关的的数据集、数据源是什么类型的？

**Comment by moncat2005** [comment]
数据集就是普通表格列表，例如相关物联器件的数值滚动展示。通过API接口的数据源，实现数据集周期更新。
仪表板上划分板块嵌入滚动，原本是指定仪表板各板块的更新频率的（5分钟），并不是刷新浏览器。
现在只有饼图之类的数据更新显示仍然正常，表格部分则全部报错。

**Comment by moncat2005** [comment]
更新1.18.18版本后，确认此问题已得到解决。
