### ISSUE TITLE
[Bug]v1.18.18无法启动，换回v1.18.17正常

### ISSUE THREAD

**Issue by sundaqiang** [dataease/dataease#9274]
**DataEase 版本**
v1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
docker

**浏览器版本**

**Bug 描述**
v1.18.18无法启动，换回v1.18.17正常
下面是日志最后的error

2024-04-23 15:16:39,583  INFO ConditionEvaluationReportLoggingListener: 136 - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-04-23 15:16:39,605 ERROR g.springframework.boot.SpringApplication: 856 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Schema `de_7s7sch` contains a failed migration to version 63 !
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at io.dataease.Application.main(Application.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.flywaydb.core.api.FlywayException: Schema `de_7s7sch` contains a failed migration to version 63 !
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:282)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:56)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:207)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:204)
	at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:161)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:204)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:165)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:215)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:164)
	at org.flywaydb.core.Flyway.execute(Flyway.java:538)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:164)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	... 27 common frames omitted

**Comment by sundaqiang** [comment]
没人在吗？

**Comment by hapeacock** [comment]
我也是1.18.18用不了。我用1panel部署的。显示启动绿色。打不开页面  CPU占用359%。 
1.18.17又没有了

**Comment by zhong914** [comment]
我也是，升级上去就炸了，使用1panel的备份恢复也还是不能用，直接全新安装18版本也提示migration to version 63异常，救命

**Comment by sundaqiang** [comment]
> 我也是，升级上去就炸了，使用1panel的备份恢复也还是不能用，直接全新安装18版本也提示migration to version 63异常，救命

手动降级吧，但是1.18.17又不能用ch

**Comment by sundaqiang** [comment]
> 我也是1.18.18用不了。我用1panel部署的。显示启动绿色。打不开页面 CPU占用359%。 1.18.17又没有了

手动修改docker-compose.yml后重建

**Comment by zhong914** [comment]
> > 我也是，升级上去就炸了，使用1panel的备份恢复也还是不能用，直接全新安装18版本也提示migration to version 63异常，救命
> 
> 手动降级吧，但是1.18.17又不能用ch

我还回去也不能用了，提示

### Error querying database. Cause: java.sql.SQLSyntaxErrorException: FUNCTION dataeasev1.GET_V_AUTH_MODEL_ID_P_USE does not exist ### The error may exist in io/dataease/ext/ExtVAuthModelMapper.xml ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: SELECT v_auth_model.id, v_auth_model.name, v_auth_model.label, v_auth_model.pid, v_auth_model.node_type, v_auth_model.model_type, v_auth_model.model_inner_type, v_auth_model.auth_type, v_auth_model.create_by, v_auth_m

论坛说是大小写问题，我改了也没用，这些函数后面发现确实不在了，自己手动迁移过去也还是不能用，😩

**Comment by sundaqiang** [comment]
https://github.com/dataease/dataease/blob/v1.18/core/backend/src/main/resources/db/migration/V63__1.18.18-data-fill.sql
问题在这个sql文件最后面的310行之后的语句，他固定了数据库名为dataease导致了sql执行失败。

修复办法
1.复制V63__1.18.18-data-fill.sql的内容，替换掉dataease.成空。
2.在数据库执行这些语句，因为之前可能执行过了，所以227-240这些也许也会报错，删掉就行
3.将dataease_version表的version=63这行的success改成1

**Comment by fit2cloud** [comment]
> https://github.com/dataease/dataease/blob/v1.18/core/backend/src/main/resources/db/migration/V63__1.18.18-data-fill.sql 问题在这个sql文件最后面的310行之后的语句，他固定了数据库名为dataease导致了sql执行失败。
> 
> 修复办法 1.复制V63__1.18.18-data-fill.sql的内容，替换掉dataease.成空。 2.在数据库执行这些语句，因为之前可能执行过了，所以227-240这些也许也会报错，删掉就行 3.将dataease_version表的version=63这行的success改成1

已升级的同学请参考这个，这个是正确的解决方案。
之前我们在dev分支上修复了，v1.18分支的代码也做了修复。
